# Is the System Stacked Against You?

At this point in the course, you’ve seen how variance in outcomes can be understood in terms of random, or noisy, statistical processes. If you bet on red at the roulette table five times in a row, and if you lose five times, that doesn’t mean the roulette wheel isn’t fair. That just could be bad luck (for you; possibly good luck for someone else who betted on black). Of course, the casino odds are stacked against you in the long run, since the casino always has an edge. For example, bets on red or black have even odds, but there are two out of 38 possible roulette outcomes in which neither black nor red will win. Now, in principle everyone knows that this is how casinos work, and indeed why they are able to stay in business. So if you end up losing more often than you win in a casino, you can only blame yourself.

Sometimes, though, outcomes are distributed in a certain way that causes us to question whether everything is indeed working as it is supposed to be, at least according to the rules of probability. In particular, when outcomes differ for some group or groups of people, we sometimes worry if the system is fair. You may have heard people say, the system isn’t fair.
Well, sometimes it isn’t, we might be able to identify an issue problem and even fix it. For this to work, though, we need to understand what outcomes are fair outcomes, and this turns out to be a complicated issue!

Let’s start with a simple example, though, to remind ourselves about sampling and differences. We’ll walk through this example very naively on purposes. Suppose we take 100 NBA basketball players as a sample and a 100 NYU graduate students as another sample, and now we look at the distribution of heights in each of our samples. We’ll look at male graduate students, since the NBA players are also males [show actual data here]. I don’t think any of you are surprised to see that there is a big difference here; that NBA players are, on average, 10 inches taller in fact. If someone asked you, what are the chances of a difference in samples like this occuring by chance, you can actually calculate an answer to that question. Food for thought: What would you need to know as inputs to that estimation?

Pause the video to think about the question and pick an answer: 
Which of the following would you need to estimate the chances of the difference in height occuring by chance?
Group sample means
Group sample variances
Sample size of groups
1 & 2 only
2 & 3 only
1 & 3 only
1, 2, & 3

Now, suppose we accept that NBA players are systematically taller. Could it be that the NBA makes people taller? Perhaps there is special practice or vitamin supplements that NBA players use that causes them to grow 10 inches? Well, we could rule this out if, for example, we examined the heights of NBA players just BEFORE they became NBA players. If we did that, we would see that they were already tall. Now, of course we knew this, but again, it’s informative to reason through this simple example as though we didn’t necessarily know. Another possibility, then, is that NBA players are selected for their being tall. Okay, let’s suppose we convince ourselves that it is true. The question we might now ask, though, is: is that fair? We’re saying that short people have a low likelihood of being hired as NBA players. (Note that we’re not suggesting that being tall is sufficient to become an NBA player, but it does seem to be necessary). What do you think? Pause the video again to respond to the following:

Which of these statements do you most agree with?
It is not fair; everyone should have an equal chance to play in the NBA
It is not fair; shorter people, who are otherwise talented in basketball, should have an equal chance to play in the NBA
It is fair; tall players perform better because their height provides an advantage in the game of basketball 
It is fair; tall players look better on the court than short players
It is neither fair nor unfair; it just is.

While I’m not saying it isn’t possible to defend different answers to this particular question of fairness, most of us agree that professional sports are by design selective on performance. In a game like basketball, height provides an advantage which, along with athleticism, makes a player perform better. We might even draw this set of claims this way:

Athleticism → 
Height → Performance →  NBA

Week 11 Video 2
It makes sense that players in the NBA would be selected for height, since height impacts performance in basketball. So professional basketball players are more likely to be tall. What if I told you that professional hockey players are more likely to be….born in the first three months of the calendar year. What? Yes, you heard that right. 

Okay, let’s work through this idea similarly to the way we did when sampling from the NBA.
But first, we need to know: in which months are babies born…
https://www.cdc.gov/nchs/fastats/births.htm

Let’s take a look at this table of births by month in the United States from 2017. Let’s concentrate on the number of births alone and in particular on the first four months of the year, January, Feb, March, and April. Pause the video to consider the following question: 

What do you think is the most plausible explanation for the variation in the the number of births in each of these four months
There is chance variation is any random process, such as childbirth
Odd numbered months are more likely to have higher birth numbers
Births are likely to go up and down in month-long cycles 
The number of days in each of the first four months of 2017* is 31, 28, 31, 30
(*) Not a leap year
Answer key:
While true, the size of the variation between these months is much too large to be explained by chance alone. Sample size is key here! Indeed if January and February were each equally likely, and we observed only 600 births in total instead of 600,000, then the chance of observing 313 or more births in one month or the other is actually about 27%. That is, there’s about a 13.5% chance or January having more than 313 births and a 13.5% chance of it having fewer than 287 births (the rest going to February). However, even if we just up the sample to 6000, the chance of observing more than 3130 births in one month or the other goes down to about 0.05%, while for 600,000 births, the chances of a discrepancy this large is a number so small it has no meaningful interpretation. So, in short, chance alone can’t explain it.

No, you probably guessed that the length of each month explains most of this effect. But not ALL of it. If every day of the year were equally likely, we can estimate the number of expected births using 3855500/365 = 10563. How many births would we expect in a month that had 30 days? [pause] Well, for months with 31 days, we would expect 31*10563 = 327453 births (rounding), for months with 28 days, 295764. Notice that the difference is large. Notice also, though, that it’s larger than the observed difference, and that each of the observed monthly birth counts are lower than expected. That must mean that some months get MORE births. And indeed this is true. Just look at July-October



So, we’ve established that there are more births in the third quarter of the year (July-Sep) than in the first quarter (Jan-Mar). Now that we’ve had a chance to think about what we might expect if there is no bias in birthday months of professional hockey players, it’s time to investigate this in a little more detail.  

Resource: https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0057753
