# Coronavirus 2020

The original plan for topics this week in the "Is the System Fair?" module was going to be academic outcomes and testing. However, the unforeseen and massively disruptive coronavirus pandemic is upon us, and it seemed worthwhile to use this opportunity to explore current events instead. Although Madonna may have called COVID-19 "the great equalizer" (https://pagesix.com/2020/03/22/madonna-calls-coronavirus-the-great-equalizer-in-bizarre-bathtub-video/), others have highlighted some data that suggest the opposite may be true. That is, COVID-19 may not be affecting all groups with the same severity. What does that mean, and is it evidence of unfairness?

New York City, in particular, has emerged as the epicenter of the US outbreak, claiming over 14,000 lives as of the time of this writing. As specific data have become available, researchers and reporters have examined counts of coronavirus infections and/or deaths by zip code and borough, by age and race. In this chapter, we will take a closer look at the data and the media reports.

Reports and Media articles:

https://theintercept.com/2020/04/09/nyc-coronavirus-deaths-race-economic-divide/
https://abcnews.go.com/Health/nyc-stark-contrast-covid-19-infection-rates-based/story?id=69920706
https://furmancenter.org/thestoop/entry/covid-19-cases-in-new-york-city-a-neighborhood-level-analysis
https://gothamist.com/news/coronavirus-statistics-tracking-epidemic-new-york


Sources for data:

https://www1.nyc.gov/site/doh/covid/covid-19-data-archive.page
https://github.com/nychealth/coronavirus-data


Factors:
Sex
Age
Race
Wealth




