<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 14 Differences in athletics | Carpe Datum</title>
  <meta name="description" content="Chapter 14 Differences in athletics | Carpe Datum" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 14 Differences in athletics | Carpe Datum" />
  <meta property="og:type" content="book" />
  
  
  
  <meta name="github-repo" content="ybergner/carpe-datum" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 14 Differences in athletics | Carpe Datum" />
  
  
  

<meta name="author" content="Yoav Bergner" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="is-the-system-fair.html"/>
<link rel="next" href="nyc-covid-19-data.html"/>
<script src="libs/header-attrs-2.7/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Carpe Datum: Data Science for Life's Big Questions</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#caveat"><i class="fa fa-check"></i>Caveat</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#guiding-principles-in-this-book"><i class="fa fa-check"></i>Guiding principles in this book</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#question-driven"><i class="fa fa-check"></i>Question-driven</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#no-proofs"><i class="fa fa-check"></i>No proofs</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="how-many-kinds-of-people-are-there.html"><a href="how-many-kinds-of-people-are-there.html"><i class="fa fa-check"></i>How Many Kinds of People Are There?</a>
<ul>
<li class="chapter" data-level="" data-path="how-many-kinds-of-people-are-there.html"><a href="how-many-kinds-of-people-are-there.html#things-are-about-to-get-meta-right-from-the-start"><i class="fa fa-check"></i>Things are about to get meta right from the start</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="categories.html"><a href="categories.html"><i class="fa fa-check"></i><b>1</b> Categories, counts, and kinds</a>
<ul>
<li class="chapter" data-level="" data-path="categories.html"><a href="categories.html#two-kinds-of-people"><i class="fa fa-check"></i>Two Kinds of People</a></li>
<li class="chapter" data-level="" data-path="categories.html"><a href="categories.html#samples-and-populations-a-statistical-caveat"><i class="fa fa-check"></i>Samples and Populations: A Statistical Caveat</a></li>
<li class="chapter" data-level="" data-path="categories.html"><a href="categories.html#a-psychological-caveat"><i class="fa fa-check"></i>A Psychological Caveat</a></li>
<li class="chapter" data-level="" data-path="categories.html"><a href="categories.html#summarizing-data"><i class="fa fa-check"></i>Summarizing data</a></li>
<li class="chapter" data-level="" data-path="categories.html"><a href="categories.html#checkpoint"><i class="fa fa-check"></i>Checkpoint</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="dimensions.html"><a href="dimensions.html"><i class="fa fa-check"></i><b>2</b> Dimensions</a>
<ul>
<li class="chapter" data-level="" data-path="dimensions.html"><a href="dimensions.html#independence-association-and-contingency"><i class="fa fa-check"></i>Independence, Association, and Contingency</a></li>
<li class="chapter" data-level="" data-path="dimensions.html"><a href="dimensions.html#latent-factors-and-measurement"><i class="fa fa-check"></i>Latent Factors and Measurement</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="test-indep.html"><a href="test-indep.html"><i class="fa fa-check"></i><b>3</b> Tests of independence: A first look starring alternate universes</a>
<ul>
<li class="chapter" data-level="" data-path="test-indep.html"><a href="test-indep.html#rise-of-the-machines"><i class="fa fa-check"></i>Rise of the machines</a></li>
<li class="chapter" data-level="" data-path="test-indep.html"><a href="test-indep.html#hypothesis-testing-just-happened"><i class="fa fa-check"></i>Hypothesis testing just happened</a></li>
<li class="chapter" data-level="" data-path="test-indep.html"><a href="test-indep.html#caveats"><i class="fa fa-check"></i>Caveats</a></li>
<li class="chapter" data-level="" data-path="test-indep.html"><a href="test-indep.html#sampling-simulations-and-randomness"><i class="fa fa-check"></i>Sampling, simulations, and randomness</a>
<ul>
<li class="chapter" data-level="" data-path="test-indep.html"><a href="test-indep.html#tossing-virtual-coins"><i class="fa fa-check"></i>Tossing (virtual) coins</a></li>
<li><a href="test-indep.html#but-some-observations-do-occur-more-than-others">But some observations <em>do</em> occur more than others</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="test-indep.html"><a href="test-indep.html#recap"><i class="fa fa-check"></i>Recap</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="shades.html"><a href="shades.html"><i class="fa fa-check"></i><b>4</b> (An Infinite Number of) Shades of Gray (or Brown)</a>
<ul>
<li class="chapter" data-level="" data-path="shades.html"><a href="shades.html#poopiness"><i class="fa fa-check"></i>Poopiness</a>
<ul>
<li class="chapter" data-level="" data-path="shades.html"><a href="shades.html#mixtures"><i class="fa fa-check"></i>Mixtures</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="shades.html"><a href="shades.html#crappiness"><i class="fa fa-check"></i>Crappiness</a>
<ul>
<li class="chapter" data-level="" data-path="shades.html"><a href="shades.html#check-your-understanding"><i class="fa fa-check"></i>Check your understanding</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="cut-scores-and-abnormality.html"><a href="cut-scores-and-abnormality.html"><i class="fa fa-check"></i><b>5</b> Cut Scores and Abnormality</a></li>
<li class="chapter" data-level="6" data-path="the-modal-american.html"><a href="the-modal-american.html"><i class="fa fa-check"></i><b>6</b> The Modal American</a>
<ul>
<li class="chapter" data-level="" data-path="the-modal-american.html"><a href="the-modal-american.html#step-one-categories"><i class="fa fa-check"></i>Step one: categories</a></li>
<li class="chapter" data-level="" data-path="the-modal-american.html"><a href="the-modal-american.html#step-two-contingency-table"><i class="fa fa-check"></i>Step two: contingency table</a></li>
<li class="chapter" data-level="" data-path="the-modal-american.html"><a href="the-modal-american.html#exercises"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="sixteen-personalities-or-five-factors.html"><a href="sixteen-personalities-or-five-factors.html"><i class="fa fa-check"></i><b>7</b> Sixteen Personalities or Five Factors?</a>
<ul>
<li class="chapter" data-level="" data-path="sixteen-personalities-or-five-factors.html"><a href="sixteen-personalities-or-five-factors.html#mbti"><i class="fa fa-check"></i>MBTI</a></li>
<li class="chapter" data-level="" data-path="sixteen-personalities-or-five-factors.html"><a href="sixteen-personalities-or-five-factors.html#big-five"><i class="fa fa-check"></i>Big Five</a></li>
<li class="chapter" data-level="" data-path="sixteen-personalities-or-five-factors.html"><a href="sixteen-personalities-or-five-factors.html#twenty-questions-about-extraversion"><i class="fa fa-check"></i>Twenty Questions (about Extraversion)</a></li>
<li class="chapter" data-level="" data-path="sixteen-personalities-or-five-factors.html"><a href="sixteen-personalities-or-five-factors.html#but-whats-the-point"><i class="fa fa-check"></i>But what’s the point?</a></li>
<li class="chapter" data-level="" data-path="sixteen-personalities-or-five-factors.html"><a href="sixteen-personalities-or-five-factors.html#recap-1"><i class="fa fa-check"></i>Recap</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="when-and-how-will-you-die.html"><a href="when-and-how-will-you-die.html"><i class="fa fa-check"></i><b>8</b> When and How Will You Die?</a>
<ul>
<li class="chapter" data-level="" data-path="when-and-how-will-you-die.html"><a href="when-and-how-will-you-die.html#not-quite-death-but-um-rain"><i class="fa fa-check"></i>Not Quite Death, but, um… Rain?</a>
<ul>
<li class="chapter" data-level="" data-path="when-and-how-will-you-die.html"><a href="when-and-how-will-you-die.html#stochastic-vs-deterministic-relationships"><i class="fa fa-check"></i>Stochastic vs Deterministic relationships</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="when-and-how-will-you-die.html"><a href="when-and-how-will-you-die.html#ways-of-thinking-about-probabilistic-statements"><i class="fa fa-check"></i>Ways of thinking about probabilistic statements</a>
<ul>
<li class="chapter" data-level="" data-path="when-and-how-will-you-die.html"><a href="when-and-how-will-you-die.html#ensembles"><i class="fa fa-check"></i>Ensembles</a></li>
<li class="chapter" data-level="" data-path="when-and-how-will-you-die.html"><a href="when-and-how-will-you-die.html#degree-of-belief"><i class="fa fa-check"></i>Degree of belief</a></li>
<li class="chapter" data-level="" data-path="when-and-how-will-you-die.html"><a href="when-and-how-will-you-die.html#decisions"><i class="fa fa-check"></i>Decisions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="when-and-how-will-you-die.html"><a href="when-and-how-will-you-die.html#death"><i class="fa fa-check"></i>Death</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="conditional-death.html"><a href="conditional-death.html"><i class="fa fa-check"></i><b>9</b> Conditional Death</a>
<ul>
<li class="chapter" data-level="" data-path="conditional-death.html"><a href="conditional-death.html#how-does-the-death-simulation-work"><i class="fa fa-check"></i>How does the death (simulation) work?</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="somefacts.html"><a href="somefacts.html"><i class="fa fa-check"></i><b>10</b> Some facts about Probabilities</a>
<ul>
<li class="chapter" data-level="" data-path="somefacts.html"><a href="somefacts.html#conditional-probabilities"><i class="fa fa-check"></i>Conditional Probabilities</a></li>
<li class="chapter" data-level="" data-path="somefacts.html"><a href="somefacts.html#conditional-death-again"><i class="fa fa-check"></i>Conditional death, again</a>
<ul>
<li class="chapter" data-level="" data-path="somefacts.html"><a href="somefacts.html#just-to-make-things-weird"><i class="fa fa-check"></i>Just to make things weird</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="how-you-will-die-causes-or-conditions.html"><a href="how-you-will-die-causes-or-conditions.html"><i class="fa fa-check"></i><b>11</b> How You Will Die: Causes or Conditions?</a>
<ul>
<li class="chapter" data-level="" data-path="how-you-will-die-causes-or-conditions.html"><a href="how-you-will-die-causes-or-conditions.html#causes-of-death-colloquially"><i class="fa fa-check"></i>Causes of death, colloquially</a></li>
<li class="chapter" data-level="" data-path="how-you-will-die-causes-or-conditions.html"><a href="how-you-will-die-causes-or-conditions.html#hold-my-beer"><i class="fa fa-check"></i>Hold my beer</a></li>
<li class="chapter" data-level="" data-path="how-you-will-die-causes-or-conditions.html"><a href="how-you-will-die-causes-or-conditions.html#non-deterministic-causation"><i class="fa fa-check"></i>Non-deterministic Causation</a></li>
<li class="chapter" data-level="" data-path="how-you-will-die-causes-or-conditions.html"><a href="how-you-will-die-causes-or-conditions.html#testing-for-an-association-between-two-variables"><i class="fa fa-check"></i>Testing for an association between two variables</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="will-you-make-money.html"><a href="will-you-make-money.html"><i class="fa fa-check"></i>Will You Make Money?</a>
<ul>
<li class="chapter" data-level="" data-path="will-you-make-money.html"><a href="will-you-make-money.html#battle-of-the-bills"><i class="fa fa-check"></i>Battle of the Bills</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="betting-on-beer-or-ice-cream.html"><a href="betting-on-beer-or-ice-cream.html"><i class="fa fa-check"></i><b>12</b> Betting on Beer (or Ice Cream)</a>
<ul>
<li class="chapter" data-level="" data-path="betting-on-beer-or-ice-cream.html"><a href="betting-on-beer-or-ice-cream.html#how-do-statisticians-solve-problems-like-this"><i class="fa fa-check"></i>How do statisticians solve problems like this?</a>
<ul>
<li class="chapter" data-level="" data-path="betting-on-beer-or-ice-cream.html"><a href="betting-on-beer-or-ice-cream.html#the-solution-by-counting-or-combinatorics"><i class="fa fa-check"></i>The solution by counting, or combinatorics</a></li>
<li class="chapter" data-level="" data-path="betting-on-beer-or-ice-cream.html"><a href="betting-on-beer-or-ice-cream.html#the-solution-by-distribution-or-statistics"><i class="fa fa-check"></i>The solution by distribution, or statistics</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="expected-value.html"><a href="expected-value.html"><i class="fa fa-check"></i><b>13</b> Expected Value</a>
<ul>
<li class="chapter" data-level="" data-path="expected-value.html"><a href="expected-value.html#betting-on-ice-cream"><i class="fa fa-check"></i>Betting on ice cream</a>
<ul>
<li class="chapter" data-level="" data-path="expected-value.html"><a href="expected-value.html#by-the-statistical-power-of-grayskull"><i class="fa fa-check"></i>By the (Statistical) Power of Grayskull</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="expected-value.html"><a href="expected-value.html#betting-on-your-future"><i class="fa fa-check"></i>Betting on your Future</a>
<ul>
<li class="chapter" data-level="" data-path="expected-value.html"><a href="expected-value.html#why-why-why-multiply-ay-ay"><i class="fa fa-check"></i>Why why why multiply-ay-ay?</a></li>
<li class="chapter" data-level="" data-path="expected-value.html"><a href="expected-value.html#where-do-branching-probabilities-come-from"><i class="fa fa-check"></i>Where do branching probabilities come from?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="is-the-system-fair.html"><a href="is-the-system-fair.html"><i class="fa fa-check"></i>Is the System Fair?</a></li>
<li class="chapter" data-level="14" data-path="differences-in-athletics.html"><a href="differences-in-athletics.html"><i class="fa fa-check"></i><b>14</b> Differences in athletics</a>
<ul>
<li class="chapter" data-level="" data-path="differences-in-athletics.html"><a href="differences-in-athletics.html#are-professional-basketball-players-taller"><i class="fa fa-check"></i>Are professional basketball players taller?</a>
<ul>
<li class="chapter" data-level="" data-path="differences-in-athletics.html"><a href="differences-in-athletics.html#none-of-this-is-surprising"><i class="fa fa-check"></i>None of this is surprising</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="differences-in-athletics.html"><a href="differences-in-athletics.html#surprising-differences"><i class="fa fa-check"></i>Surprising differences</a></li>
<li class="chapter" data-level="" data-path="differences-in-athletics.html"><a href="differences-in-athletics.html#fairness-on-trial-trans-athletes"><i class="fa fa-check"></i>Fairness on trial: trans athletes</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="nyc-covid-19-data.html"><a href="nyc-covid-19-data.html"><i class="fa fa-check"></i><b>15</b> NYC COVID-19 Data</a>
<ul>
<li class="chapter" data-level="" data-path="nyc-covid-19-data.html"><a href="nyc-covid-19-data.html#prologue"><i class="fa fa-check"></i>Prologue</a></li>
<li class="chapter" data-level="15.1" data-path="nyc-covid-19-data.html"><a href="nyc-covid-19-data.html#part1"><i class="fa fa-check"></i><b>15.1</b> COVID NYC</a>
<ul>
<li class="chapter" data-level="" data-path="nyc-covid-19-data.html"><a href="nyc-covid-19-data.html#getting-some-data"><i class="fa fa-check"></i>Getting some data</a></li>
<li class="chapter" data-level="" data-path="nyc-covid-19-data.html"><a href="nyc-covid-19-data.html#local-data-on-covid-from-the-city-andor-state"><i class="fa fa-check"></i>Local data on COVID from the city and/or state</a></li>
</ul></li>
<li class="chapter" data-level="15.2" data-path="nyc-covid-19-data.html"><a href="nyc-covid-19-data.html#part2"><i class="fa fa-check"></i><b>15.2</b> Getting started with US Census data</a>
<ul>
<li class="chapter" data-level="" data-path="nyc-covid-19-data.html"><a href="nyc-covid-19-data.html#census-variables"><i class="fa fa-check"></i>Census Variables</a></li>
<li class="chapter" data-level="" data-path="nyc-covid-19-data.html"><a href="nyc-covid-19-data.html#geography-units"><i class="fa fa-check"></i>Geography Units</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="nyc-covid-19-data.html"><a href="nyc-covid-19-data.html#part3"><i class="fa fa-check"></i><b>15.3</b> More (and messier) Census data</a>
<ul>
<li class="chapter" data-level="" data-path="nyc-covid-19-data.html"><a href="nyc-covid-19-data.html#exploring-the-acs-data"><i class="fa fa-check"></i>Exploring the ACS data</a></li>
</ul></li>
<li class="chapter" data-level="15.4" data-path="nyc-covid-19-data.html"><a href="nyc-covid-19-data.html#zipcode"><i class="fa fa-check"></i><b>15.4</b> Zipcode tabulation area</a>
<ul>
<li class="chapter" data-level="" data-path="nyc-covid-19-data.html"><a href="nyc-covid-19-data.html#some-more-variables-to-play-with"><i class="fa fa-check"></i>Some more variables to play with</a></li>
</ul></li>
<li class="chapter" data-level="15.5" data-path="nyc-covid-19-data.html"><a href="nyc-covid-19-data.html#mapviz"><i class="fa fa-check"></i><b>15.5</b> Visualizing data on maps</a>
<ul>
<li class="chapter" data-level="" data-path="nyc-covid-19-data.html"><a href="nyc-covid-19-data.html#shapefiles"><i class="fa fa-check"></i>Shapefiles</a></li>
<li class="chapter" data-level="" data-path="nyc-covid-19-data.html"><a href="nyc-covid-19-data.html#coloring-in-the-shapes"><i class="fa fa-check"></i>Coloring in the shapes</a></li>
<li class="chapter" data-level="" data-path="nyc-covid-19-data.html"><a href="nyc-covid-19-data.html#scatterplots"><i class="fa fa-check"></i>Scatterplots</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="16" data-path="gerrymandering.html"><a href="gerrymandering.html"><i class="fa fa-check"></i><b>16</b> Gerrymandering</a>
<ul>
<li class="chapter" data-level="" data-path="gerrymandering.html"><a href="gerrymandering.html#how-to-play-the-gerrymandering-game"><i class="fa fa-check"></i>How to play the gerrymandering game</a></li>
<li class="chapter" data-level="" data-path="gerrymandering.html"><a href="gerrymandering.html#the-politics-of-gerrymandering"><i class="fa fa-check"></i>The politics of gerrymandering</a></li>
<li class="chapter" data-level="" data-path="gerrymandering.html"><a href="gerrymandering.html#the-math-of-gerrymandering"><i class="fa fa-check"></i>The math of gerrymandering</a>
<ul>
<li class="chapter" data-level="" data-path="gerrymandering.html"><a href="gerrymandering.html#unfairness-as-deviation-from-expected-outcomes-under-fair-play"><i class="fa fa-check"></i>Unfairness as deviation from expected outcomes under fair play</a></li>
<li class="chapter" data-level="" data-path="gerrymandering.html"><a href="gerrymandering.html#this-just-might-work"><i class="fa fa-check"></i>This just might work</a></li>
<li class="chapter" data-level="" data-path="gerrymandering.html"><a href="gerrymandering.html#the-combinatorics-of-gerrymandering"><i class="fa fa-check"></i>The combinatorics of gerrymandering</a></li>
<li class="chapter" data-level="" data-path="gerrymandering.html"><a href="gerrymandering.html#move-over-brute-force-hello-random-walk-sampling"><i class="fa fa-check"></i>Move over brute force, hello random walk sampling</a></li>
<li class="chapter" data-level="" data-path="gerrymandering.html"><a href="gerrymandering.html#seat-count-is-not-the-only-or-most-common-outcome-measure"><i class="fa fa-check"></i>Seat-count is not the only (or most common) outcome measure</a></li>
</ul></li>
</ul></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="sec-randomness.html"><a href="sec-randomness.html"><i class="fa fa-check"></i><b>A</b> Randomness</a>
<ul>
<li class="chapter" data-level="A.1" data-path="sec-randomness.html"><a href="sec-randomness.html#defining-random-processes"><i class="fa fa-check"></i><b>A.1</b> Defining random processes</a></li>
<li class="chapter" data-level="A.2" data-path="sec-randomness.html"><a href="sec-randomness.html#predictions-about-random-events"><i class="fa fa-check"></i><b>A.2</b> Predictions about random events</a></li>
<li class="chapter" data-level="A.3" data-path="sec-randomness.html"><a href="sec-randomness.html#modification-for-continuous-observations"><i class="fa fa-check"></i><b>A.3</b> Modification for continuous observations</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Carpe Datum</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="differences-in-athletics" class="section level1" number="14">
<h1><span class="header-section-number">Chapter 14</span> Differences in athletics</h1>
<!-- Not everyone excels at sports to the same degree. As data scientists, we might say that athletic ability is not constant, but rather variable. It is distributed. Like many other things that vary across people, this  -->
<div id="are-professional-basketball-players-taller" class="section level2 unnumbered">
<h2>Are professional basketball players taller?</h2>
<p>Let’s start with an example to refresh your memory about sampling and differences. We’ll walk through this example very naively on purpose. Suppose we take 100 NBA basketball players as a sample (of all basketball players) and 100 NYU students as another sample (of NYU students), and now we look at the distribution of heights in each of our samples. We’ll consider male students, since the NBA players are also males. Actually, I don’t have any data on NYU student heights. So we’ll just consider all adult males. Conveniently, the <code>openintro</code> R package has a data set called male.heights and another data set called <code>nba.heights</code>. You can load them as follows</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="differences-in-athletics.html#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(openintro)</span>
<span id="cb78-2"><a href="differences-in-athletics.html#cb78-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;male_heights&quot;</span>)</span>
<span id="cb78-3"><a href="differences-in-athletics.html#cb78-3" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;nba_heights&quot;</span>)</span></code></pre></div>
<p>And then you can inspect them. For example, one of the first things I will do with a data set is ask how big it is (how many rows and columns) and then look at the first few rows.</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="differences-in-athletics.html#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(male_heights)</span></code></pre></div>
<pre><code>## [1] 100   1</code></pre>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="differences-in-athletics.html#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(male_heights)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 1
##   heights
##     &lt;int&gt;
## 1      71
## 2      67
## 3      69
## 4      70
## 5      68
## 6      63</code></pre>
<p>The <code>male_heights</code> data table has 100 rows and a single column called “heights.” The nba.heights data set is a little different.</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="differences-in-athletics.html#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(nba_heights)</span></code></pre></div>
<pre><code>## [1] 435   4</code></pre>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="differences-in-athletics.html#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(nba_heights)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 4
##   last_name first_name h_meters  h_in
##   &lt;chr&gt;     &lt;chr&gt;         &lt;dbl&gt; &lt;int&gt;
## 1 Acker     Alex           1.96    77
## 2 Adams     Hassan         1.93    76
## 3 Afflalo   Arron          1.96    77
## 4 Ager      Maurice        1.96    77
## 5 Ajinca    Alexis         2.13    84
## 6 Aldridge  LaMarcus       2.11    83</code></pre>
<p>Notice that there are 435 NBA players from the 2008-2009 season here. We have their first and last names as well as their heights in units of meters and also inches. I’d like to make a comparison between similarly sized samples. So I will just take a subsample of 100 NBA players. I can do this easily using the <code>sample()</code> function.</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="differences-in-athletics.html#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="co"># sample 100 values at random from the nba heights in inches</span></span>
<span id="cb87-2"><a href="differences-in-athletics.html#cb87-2" aria-hidden="true" tabindex="-1"></a>nbaHeights <span class="ot">&lt;-</span> <span class="fu">sample</span>(nba_heights<span class="sc">$</span>h_in, <span class="dv">100</span>) </span>
<span id="cb87-3"><a href="differences-in-athletics.html#cb87-3" aria-hidden="true" tabindex="-1"></a><span class="co"># rename the male height to match</span></span>
<span id="cb87-4"><a href="differences-in-athletics.html#cb87-4" aria-hidden="true" tabindex="-1"></a>maleHeights <span class="ot">&lt;-</span> male_heights<span class="sc">$</span>heights</span></code></pre></div>
<p>Note that because I did not use a <code>set.seed</code> in the code above, I have no idea which 100 NBA players I got. In fact, every time I (or you) run this, I (or you) will get a different sample! Finally, I would like to compare the <em>distributions</em> of heights for these two samples. For which our old friend the histogram is just what the doctor ordered.</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="differences-in-athletics.html#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="co"># defining some colors and bin-breaks to standardize my plots</span></span>
<span id="cb88-2"><a href="differences-in-athletics.html#cb88-2" aria-hidden="true" tabindex="-1"></a>malescol <span class="ot">&lt;-</span> <span class="fu">rgb</span>(<span class="fl">0.8</span>,<span class="fl">0.2</span>,<span class="dv">0</span>,<span class="fl">0.2</span>)</span>
<span id="cb88-3"><a href="differences-in-athletics.html#cb88-3" aria-hidden="true" tabindex="-1"></a>nbacol <span class="ot">&lt;-</span> <span class="fu">rgb</span>(<span class="dv">0</span>,<span class="fl">0.3</span>,<span class="fl">0.8</span>,<span class="fl">0.2</span>)</span>
<span id="cb88-4"><a href="differences-in-athletics.html#cb88-4" aria-hidden="true" tabindex="-1"></a>mybreaks <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">54</span>,<span class="dv">90</span>,<span class="dv">3</span>)</span>
<span id="cb88-5"><a href="differences-in-athletics.html#cb88-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-6"><a href="differences-in-athletics.html#cb88-6" aria-hidden="true" tabindex="-1"></a><span class="co"># plot a histogram showing both height distributions, separately</span></span>
<span id="cb88-7"><a href="differences-in-athletics.html#cb88-7" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(maleHeights, <span class="at">col=</span>malescol, <span class="at">breaks=</span>mybreaks, </span>
<span id="cb88-8"><a href="differences-in-athletics.html#cb88-8" aria-hidden="true" tabindex="-1"></a>          <span class="at">main=</span><span class="st">&quot;Heights of males&quot;</span>, <span class="at">xlab=</span><span class="st">&quot;Height (inches)&quot;</span>)</span></code></pre></div>
<p><img src="carpedatum_files/figure-html/unnamed-chunk-33-1.png" width="90%" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="differences-in-athletics.html#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(nbaHeights, <span class="at">col=</span>nbacol, <span class="at">breaks=</span>mybreaks, </span>
<span id="cb89-2"><a href="differences-in-athletics.html#cb89-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&quot;Heights of NBA players&quot;</span>, <span class="at">xlab=</span><span class="st">&quot;Height (inches)&quot;</span>)</span></code></pre></div>
<p><img src="carpedatum_files/figure-html/unnamed-chunk-33-2.png" width="90%" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="differences-in-athletics.html#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot a histogram showing both height distributions, together (add=T)</span></span>
<span id="cb90-2"><a href="differences-in-athletics.html#cb90-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(maleHeights, <span class="at">col=</span>malescol, <span class="at">breaks=</span>mybreaks, </span>
<span id="cb90-3"><a href="differences-in-athletics.html#cb90-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">main=</span><span class="st">&quot;&quot;</span>, <span class="at">xlab=</span><span class="st">&quot;Height (inches)&quot;</span>)</span>
<span id="cb90-4"><a href="differences-in-athletics.html#cb90-4" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(nbaHeights, <span class="at">col=</span>nbacol, <span class="at">breaks=</span>mybreaks, <span class="at">add=</span>T)</span>
<span id="cb90-5"><a href="differences-in-athletics.html#cb90-5" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;topleft&quot;</span>, <span class="fu">c</span>(<span class="st">&quot;non-NBA&quot;</span>, <span class="st">&quot;NBA&quot;</span>), <span class="at">fill =</span> <span class="fu">c</span>(malescol, nbacol))</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:compareheights"></span>
<img src="carpedatum_files/figure-html/compareheights-1.png" alt="Histogram of NBA and non-NBA male heights on one plot using transparent colors" width="90%" />
<p class="caption">
Figure 14.1: Histogram of NBA and non-NBA male heights on one plot using transparent colors
</p>
</div>
<p>I have shown three histograms, one with only the males dataset, one with only the NBA data set, and one showing both groups at the same time. I’ve made the colors in R slightly transparent, so that both distributions are visible at the same time. But it is very important to recognize that in Figure <a href="differences-in-athletics.html#fig:compareheights">14.1</a>, we are seeing an overlap region of two distributions, <em>not</em> three distributions shown with “stacked bars.” You sometimes see stacked barplots, where the height of the bar is the total count, and the colors represent contributions to the total from different groups. For example, units sold in the USA and units sold abroad = total units sold. Here, you don’t see the total. You would have to estimate it by mentally adding up the <em>full heights</em> of each bar. So, for example, the total number (out of 200) of males in the height range of 72-75 inches would be 14 from the males data set plus 17 from the NBA dataset.</p>
<p>I doubt any of you reading this are surprised to see that there is a big difference in these distributions; that NBA players are, on average, 9 or 10 inches taller than the (average) males. For the particular subsample I’ve drawn, the difference happens to be exactly 9.5 inches.</p>
<p>Now that you are somewhat conversant with sampling variation, you might wonder: what are the chances of a difference in sample heights like this occuring by chance? After all, if we had a large group of males to begin with, and we sampled from them two different times, we would not expect the averages of the two samples to be identical. We will probably get a taller sample and a shorter sample, right? But how much taller?</p>
<p>You can actually simulate and/or calculate an answer to these questions. Which of the following would you need to know in order to estimate the chances of a large difference in height occuring by chance?</p>
<ol style="list-style-type: decimal">
<li>Group sample means (averages)</li>
<li>Group sample variances (a measure of spread)</li>
<li>Sample size of groups</li>
</ol>
<ol style="list-style-type: upper-alpha">
<li>1 &amp; 2 only</li>
<li>2 &amp; 3 only</li>
<li>1 &amp; 3 only</li>
<li>1, 2, &amp; 3</li>
</ol>
<p>Answer.<a href="#fn11" class="footnote-ref" id="fnref11"><sup>11</sup></a></p>
<p>We can go to the National Center for Health Statistics website to retrieve a larger census of male heights. (You can find Body Measures in the National Health and Nutrition Examination Survey conducted every two years.) Conveniently (again) someone has even made an R package to save you the time (<code>NHANES</code>). The data set includes females as well as children, so I will filter those out. Here is a distribution of roughly 3600 males.</p>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="differences-in-athletics.html#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(NHANES) <span class="co">#</span></span>
<span id="cb91-2"><a href="differences-in-athletics.html#cb91-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb91-3"><a href="differences-in-athletics.html#cb91-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb91-4"><a href="differences-in-athletics.html#cb91-4" aria-hidden="true" tabindex="-1"></a>lotsoheights <span class="ot">&lt;-</span> NHANES <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Gender <span class="sc">==</span> <span class="st">&quot;male&quot;</span> <span class="sc">&amp;</span> Age <span class="sc">&gt;</span> <span class="dv">18</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb91-5"><a href="differences-in-athletics.html#cb91-5" aria-hidden="true" tabindex="-1"></a>                                <span class="fu">select</span>(Height) <span class="sc">%&gt;%</span> <span class="fu">unlist</span>() <span class="sc">%&gt;%</span> <span class="fu">na.omit</span>()</span>
<span id="cb91-6"><a href="differences-in-athletics.html#cb91-6" aria-hidden="true" tabindex="-1"></a><span class="co"># convert cm to in</span></span>
<span id="cb91-7"><a href="differences-in-athletics.html#cb91-7" aria-hidden="true" tabindex="-1"></a>lotsoheights <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(lotsoheights) <span class="sc">/</span> <span class="fl">2.54</span></span>
<span id="cb91-8"><a href="differences-in-athletics.html#cb91-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb91-9"><a href="differences-in-athletics.html#cb91-9" aria-hidden="true" tabindex="-1"></a><span class="co"># plot as before</span></span>
<span id="cb91-10"><a href="differences-in-athletics.html#cb91-10" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(lotsoheights, <span class="at">col=</span>malescol, <span class="at">breaks=</span>mybreaks, </span>
<span id="cb91-11"><a href="differences-in-athletics.html#cb91-11" aria-hidden="true" tabindex="-1"></a>          <span class="at">main=</span><span class="st">&quot;Heights of 3600 males&quot;</span>, <span class="at">xlab=</span><span class="st">&quot;Height (inches)&quot;</span>)</span></code></pre></div>
<p><img src="carpedatum_files/figure-html/unnamed-chunk-35-1.png" width="90%" style="display: block; margin: auto;" /></p>
<p>Now consider a process of sub-sampling from this larger sample repeatedly. That is, we take two samples of 100 and compare the difference in the sample averages. Let’s say we do it 1000 times. How often do we see differences as extreme as 9 inches? Mind you, we have no idea which of our two samples will turn out taller, so we’ll need to look for differences with magnitude (or absolute value) greater than 9. Because the difference could be 9.5 or -9.5 depending on the order of subtraction. Here goes:</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="differences-in-athletics.html#cb92-1" aria-hidden="true" tabindex="-1"></a>numSamples <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb92-2"><a href="differences-in-athletics.html#cb92-2" aria-hidden="true" tabindex="-1"></a>sampleSize <span class="ot">&lt;-</span> <span class="dv">100</span></span>
<span id="cb92-3"><a href="differences-in-athletics.html#cb92-3" aria-hidden="true" tabindex="-1"></a>differences_in_means <span class="ot">&lt;-</span> <span class="fu">c</span>()</span>
<span id="cb92-4"><a href="differences-in-athletics.html#cb92-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>numSamples) {</span>
<span id="cb92-5"><a href="differences-in-athletics.html#cb92-5" aria-hidden="true" tabindex="-1"></a>  sample1 <span class="ot">&lt;-</span> <span class="fu">sample</span>(lotsoheights, sampleSize)</span>
<span id="cb92-6"><a href="differences-in-athletics.html#cb92-6" aria-hidden="true" tabindex="-1"></a>  sample2 <span class="ot">&lt;-</span> <span class="fu">sample</span>(lotsoheights, sampleSize)</span>
<span id="cb92-7"><a href="differences-in-athletics.html#cb92-7" aria-hidden="true" tabindex="-1"></a>  differences_in_means <span class="ot">&lt;-</span> <span class="fu">c</span>(differences_in_means, <span class="fu">mean</span>(sample1) <span class="sc">-</span> <span class="fu">mean</span>(sample2))</span>
<span id="cb92-8"><a href="differences-in-athletics.html#cb92-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb92-9"><a href="differences-in-athletics.html#cb92-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-10"><a href="differences-in-athletics.html#cb92-10" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(differences_in_means)</span></code></pre></div>
<p><img src="carpedatum_files/figure-html/unnamed-chunk-36-1.png" width="90%" style="display: block; margin: auto;" /></p>
<p>You’ll notice that in 1000 experiments, we never observed a difference in mean heights between our two samples of even 2 inches, let alone 9 inches. Here is how you would know for sure</p>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="differences-in-athletics.html#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="co"># declare a threshold difference of interest</span></span>
<span id="cb93-2"><a href="differences-in-athletics.html#cb93-2" aria-hidden="true" tabindex="-1"></a>thresholdDiff <span class="ot">&lt;-</span> <span class="dv">9</span></span>
<span id="cb93-3"><a href="differences-in-athletics.html#cb93-3" aria-hidden="true" tabindex="-1"></a><span class="co"># compute percentage of events outside of this threshold</span></span>
<span id="cb93-4"><a href="differences-in-athletics.html#cb93-4" aria-hidden="true" tabindex="-1"></a>numExtreme <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="fu">which</span>(<span class="fu">abs</span>(differences_in_means) <span class="sc">&gt;</span> thresholdDiff))</span>
<span id="cb93-5"><a href="differences-in-athletics.html#cb93-5" aria-hidden="true" tabindex="-1"></a>percentExtreme <span class="ot">&lt;-</span> numExtreme<span class="sc">/</span>numSamples <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb93-6"><a href="differences-in-athletics.html#cb93-6" aria-hidden="true" tabindex="-1"></a><span class="fu">paste0</span>(percentExtreme,<span class="st">&quot;%&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;0%&quot;</code></pre>
<p>In short, it seems highly implausible that this difference would occur by chance.</p>
<blockquote>
<p>Exercise: modify the code to use samples of 10 instead of 100. Do you observe bigger differences? And if so, are they big enough to explain the NBA difference?</p>
</blockquote>
<blockquote>
<p>Exercise: Experiment with changing the threshold difference. Using the original sample size of 100, how often are differences greater than 1 inch? Where should the threshold be set so that a difference <em>at least as large as this threshold</em> is expected to occur roughly 25% of the time?</p>
</blockquote>
<div id="none-of-this-is-surprising" class="section level3 unnumbered">
<h3>None of this is surprising</h3>
<p>Okay, so suppose we accept that NBA players are systematically taller. Could it be that the NBA makes people taller? Perhaps there is special practice or vitamin supplement that NBA players use that causes them to grow 9-10 inches? Well, we could rule this out if, for example, we examined the heights of NBA players just BEFORE they became NBA players. If we did that, we would see that they were already tall.</p>
<p>Another possibility, then, is that NBA players are selected for being tall. The question we might now ask, though, is: is that fair? We’re saying that short people have a low likelihood of being hired as NBA players. (Note that we’re not suggesting that being tall is <em>sufficient</em> to become an NBA player, but it does seem to be <em>necessary</em>). What do you think?</p>
<p>Which of these statements do you most agree with?</p>
<ol style="list-style-type: decimal">
<li>It is not fair; everyone should have an equal chance to play in the NBA</li>
<li>It is not fair; shorter people, who are exceptionally talented in basketball, should have an equal chance to play in the NBA</li>
<li>It is fair; tall players perform better because their height provides an advantage in the game of basketball</li>
<li>It is fair; tall players look better on the court than short players, and the NBA has to sell tickets.</li>
<li>It is neither fair nor unfair; it just is.</li>
</ol>
<p>It may be possible to defend different answers to this particular question of fairness, but most of us can agree that professional sports are, by design, selective on performance. In a game like basketball, height provides an advantage which, along with athleticism (strength, speed, stamina, etc.), makes a player perform better.</p>
<p>In summary, we have observed a difference between groups. NBA players are taller than non-NBA players. This difference does not appear to be consistent with random chance. Indeed, we probably knew enough about basketball to explain the difference in terms of selection for competitive advantage. But, importantly, it is up to us to decide whether selecting players for competitive advantage—even if it means that we effectively discriminate against short athletes—is fair.</p>
<!-- We might even draw this set of claims this way: -->
<!-- Athleticism →  -->
<!-- Height → Performance →  NBA -->
</div>
</div>
<div id="surprising-differences" class="section level2 unnumbered">
<h2>Surprising differences</h2>
<p>So professional basketball players are more likely to be tall. What if I told you that professional hockey players are more likely to be….born in the first three months of the calendar year. What? Yes, you heard that right. See Figure <a href="differences-in-athletics.html#fig:hockey-fig">14.2</a> (Full paper: <a href="https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0057753" class="uri">https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0057753</a>
).</p>

<div class="figure" style="text-align: center"><span id="fig:hockey-fig"></span>
<img src="images/hockeybirths.png" alt="Percentage of NHL draftees born in the first or fourth quarter over time. Blue circles indicate first quarter; yellow triangles indicate fourth quarter. Source: Born at the Wrong Time: Selection Bias in the NHL Draft" width="70%" />
<p class="caption">
Figure 14.2: Percentage of NHL draftees born in the first or fourth quarter over time. Blue circles indicate first quarter; yellow triangles indicate fourth quarter. Source: <a href="https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0057753">Born at the Wrong Time: Selection Bias in the NHL Draft</a>
</p>
</div>
<p>Okay, let’s work through this idea similarly to the way we did when sampling from the NBA. That is, let us first consider the possibility that these differences are a result of sampling without systematic bias. As before, we need a baseline for comparison. For NBA heights, we needed to compare the distribution to non-NBA males. For hockey birth-months, we need a sense of birth-month distribution in the general population. I won’t bother distinguishing male and female births, because I don’t have any reason to believe that these occur differently month-by-month.</p>
<p>From this CDC source (<a href="https://www.cdc.gov/nchs/fastats/births.htm" class="uri">https://www.cdc.gov/nchs/fastats/births.htm</a>), I have produced a table of births by month in the United States from 2017.</p>
<table class="table table-striped table" style="width: auto !important; margin-left: auto; margin-right: auto; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:birthmonth-table">Table 14.1: </span>Births by month (USA, 2017)
</caption>
<thead>
<tr>
<th style="text-align:left;">
month
</th>
<th style="text-align:right;">
count
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
January
</td>
<td style="text-align:right;">
313786
</td>
</tr>
<tr>
<td style="text-align:left;">
February
</td>
<td style="text-align:right;">
289054
</td>
</tr>
<tr>
<td style="text-align:left;">
March
</td>
<td style="text-align:right;">
319625
</td>
</tr>
<tr>
<td style="text-align:left;">
April
</td>
<td style="text-align:right;">
300116
</td>
</tr>
<tr>
<td style="text-align:left;">
May
</td>
<td style="text-align:right;">
322456
</td>
</tr>
<tr>
<td style="text-align:left;">
June
</td>
<td style="text-align:right;">
323920
</td>
</tr>
<tr>
<td style="text-align:left;">
July
</td>
<td style="text-align:right;">
334924
</td>
</tr>
<tr>
<td style="text-align:left;">
August
</td>
<td style="text-align:right;">
352151
</td>
</tr>
<tr>
<td style="text-align:left;">
September
</td>
<td style="text-align:right;">
337175
</td>
</tr>
<tr>
<td style="text-align:left;">
October
</td>
<td style="text-align:right;">
329869
</td>
</tr>
<tr>
<td style="text-align:left;">
November
</td>
<td style="text-align:right;">
316511
</td>
</tr>
<tr>
<td style="text-align:left;">
December
</td>
<td style="text-align:right;">
315913
</td>
</tr>
</tbody>
</table>
<p>Let’s concentrate on the number of births and, in particular, on the first four months of the year, January, Feb, March, and April.</p>
<p>What do you think is the most plausible explanation for the variation in the the number of births in each of these four months?</p>
<ol style="list-style-type: lower-alpha">
<li>There is chance variation is any random process, such as childbirth</li>
<li>Odd numbered months are more likely to have higher birth numbers</li>
<li>Births are likely to go up and down in month-long cycles</li>
<li>The number of days in each of the first four months of 2017 (not a leap year) is 31, 28, 31, 30</li>
</ol>
<p>Consider option (a). While the statement itself is true, the size of the variation between these months is much too large to be explained by chance alone. Sample size is key here!</p>
<p>If January and February were each equally likely, up to random chance, and we observed only 600 births in total instead of 600,000, then the chance of observing 313 or more births in one month or the other is actually about 27%. That is, there’s about a 13.5% chance of January having more than 313 births and a 13.5% chance of it having fewer than 287 births (the rest of the 600 going to February). However, even if we just up the sample to 6000, the chance of observing more than 3130 births in one month or the other goes down to about 0.05%, while for 600,000 births, the chances of a discrepancy this large is a number so small it has no meaningful interpretation. So, in short, chance alone can’t explain it.</p>
<p>No, you probably guessed that the length of each month explains most of this effect. But not ALL of it. If every day of the year were equally likely, we can estimate the number of expected births per day as <code>3855500/365 = 10563</code>. How many births would we expect in a month that had 30 days? Well, for months with 31 days, we would expect <code>31*10563 = 327453</code> births (rounding), for months with 28 days, 295764. Notice that the difference is large. Notice also, though, that it is <em>larger</em> than the observed difference, and that observed monthly birth counts in January and February are both actually lower than expected. That must mean that some other months of the year get more births. And indeed this is true. Just look at July-October.</p>
<p>Having examined the data at the month level, we can also combine three months into quarters. Here is the quarterly count, as well as the proportion (each quarterly count divided by total).</p>
<table class="table table-striped table" style="width: auto !important; margin-left: auto; margin-right: auto; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:birthquarter">Table 14.2: </span>Births by quarter (USA, 2017)
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
count
</th>
<th style="text-align:right;">
proportion
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Q1
</td>
<td style="text-align:right;">
922465
</td>
<td style="text-align:right;">
0.239
</td>
</tr>
<tr>
<td style="text-align:left;">
Q2
</td>
<td style="text-align:right;">
946492
</td>
<td style="text-align:right;">
0.245
</td>
</tr>
<tr>
<td style="text-align:left;">
Q3
</td>
<td style="text-align:right;">
1024250
</td>
<td style="text-align:right;">
0.266
</td>
</tr>
<tr>
<td style="text-align:left;">
Q4
</td>
<td style="text-align:right;">
962293
</td>
<td style="text-align:right;">
0.250
</td>
</tr>
</tbody>
</table>
<p>Looking at this, we can see plainly that there are more births in the third quarter of the year (July-Sep) than in the first quarter (Jan-Mar). The proportions in Table <a href="differences-in-athletics.html#tab:birthquarter">14.2</a> are what we would expect to see in any collection of people (e.g., professional hockey players) <em>if they were not systematically selected for birth month</em>.</p>
<div id="aside-sampling-with-more-than-two-groups" class="section level4 unnumbered">
<h4>Aside: Sampling with more than two groups</h4>
<p>Previously in this course, for example with two-types-of-people questions and with beer taste-tests, we looked at how to simulate dichotomous outcomes. We used the <code>sample()</code> function in R repeatedly, or we took advantage of the binomial distribution. The function <code>rbinom()</code> can be used to simulate many beer taste-tests, for example, and the function <code>dbinom()</code> can be used to compute the proportion of certain outcomes. Suppose we wanted to simulate a draft of 100 hockey players, drawn from the population at random so that their birth-quarter should reflect the proportion of all births that occur in each quarter of the year. (This is necessary for the RShiny simulation this week.) This is very similar to our simulated “coin-flips” except that we have four possible outcomes. We want to roll a four-sided die, so to speak, but it is a loaded die. Not all outcomes are equally likely. This generalization of two to many is captured in the generalization of the <strong>binomial</strong> distribution to the <strong>multinomial</strong> distribution. The R function <code>rmultinom()</code> can be used like this</p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="differences-in-athletics.html#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="co"># suppose I have four possible outcomes with</span></span>
<span id="cb95-2"><a href="differences-in-athletics.html#cb95-2" aria-hidden="true" tabindex="-1"></a><span class="co"># probabilities of 0.2, 0.3, 0.4, and 0.1, respectively</span></span>
<span id="cb95-3"><a href="differences-in-athletics.html#cb95-3" aria-hidden="true" tabindex="-1"></a>simulationResults <span class="ot">&lt;-</span> <span class="fu">rmultinom</span>(<span class="dv">10</span>, <span class="dv">100</span>, <span class="at">prob=</span><span class="fu">c</span>(<span class="fl">0.2</span>, <span class="fl">0.3</span>, <span class="fl">0.4</span>, <span class="fl">0.1</span>))</span>
<span id="cb95-4"><a href="differences-in-athletics.html#cb95-4" aria-hidden="true" tabindex="-1"></a>simulationResults</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
## [1,]   21   24   23   21   19   19   26   13   27    26
## [2,]   35   23   29   28   37   17   26   32   30    31
## [3,]   38   42   37   42   33   47   44   48   38    34
## [4,]    6   11   11    9   11   17    4    7    5     9</code></pre>
<p>The output might be a little confusing. What you are seeing is the result of 10 draw trials with a sample of 100. This is the 10 columns. For each trial, I will get a certain number of samples corresponding to outcome 1, outcome 2, outcome 3, and outcome 4. These are the four rows. As the outcomes were not equally likely, I do not expect 25% in each row. I expect (because of the probabilities I specified), 20%, 30%, 40%, and 10%. In fact, you can see that there is quite a bit of sampling variability. The average over our trial is extracted as follows:</p>
<pre><code>## [1] 21.9 28.8 40.3  9.0</code></pre>
<p>Although not exactly our inputed proportions, the averages are pretty close. Which parameter do you think would make our mean value even closer if we increased it, the sample size or the number of simulations?</p>
</div>
<div id="and-now-back-to-the-issue-of-fairness" class="section level4 unnumbered">
<h4>And now back to the issue of fairness</h4>
<p>We could understand the NBA players were selected for height, because height offers a competitive advantage in basketball, other things being equal. Why would hockey players be selected for birth month? The answer lies in the structure of organized youth sports, where future athletes get their start. It is called the relative age effect (RAE).</p>
<p>In youth leagues, groups are cohorted by age, using January 1 (typically) as a cutoff date. Thus kids who are 9 years old as of January 1 would be assigned to a different group than kids who are 10 years old as of January 1. The idea makes sense, but it means that among 9-year-olds playing in the same team, those born early in the year are almost 10, while those born late in the year are almost a year younger. At this age, a difference of 9 months can mean a lot in terms of child development of strength and speed. The slightly older children may thus excel because of their relative age within their youth league. They are subsequently selected for increased attention from coaches, which further develops their ability. By the time they are fully grown, the effect of having been the bigger kid has compounded itself.</p>
<p>The relative age effect has been documented in many sports, not just hockey. Is it fair? Most people think it is not.</p>
<p>Whether you turn out tall or athletically gifted may indeed be luck. It may be genetically inherited, but from your point of view that is still luck. You didn’t earn your body. You didn’t choose what month to be born in either. But while height is an eventuality that we cannot control (nutrition aside), relative age differences are a fleeting effect (that is, they fade away over time) and are only introduced by artifical cutoffs. As a child, I was never going to grow up to be six-foot-nine. But I was surely going to grow up.</p>
<p>We need age cutoffs in youth sports; they serve a basic purpose. But we could avoid singling out the faster, stronger kids for attention by recognizing that they might be excelling in part because of their relative age. Put another way, we might want to single out kids who are born late in the year and, while not the best in the league, are still in the top performers among other kids born late in the year. That is, we would <em>condition</em> on their relative age. Doing so would be more fair and would be ultimately better for professional sports.</p>
</div>
</div>
<div id="fairness-on-trial-trans-athletes" class="section level2 unnumbered">
<h2>Fairness on trial: trans athletes</h2>
<p>We started out this chapter with an example of height differences in the NBA. Although it represents systematic bias against short people, most people don’t have a problem with it. In contrast, the disparity of birth-months in professional sports seems to indicate an unfairness, a flaw in the process that can be fixed. It is not, perhaps, always so clear cut. In recent years, the issue of trans athletes in competitive sports has become quite controversial.</p>
<p>To understand the origins of this problem, we first need to understand why sports competitions are separated into sex categories in the first place. It may seem obvious. We have all probably noticed that biological differences between males and females can affect their athletic performance. However, looking at this problem through the lens of data helps to sharpen our focus. For example, I’m not a particularly good runner. If you picked a random person my age for me to race against, I wouldn’t personally feel like my odds were that much better against a female than a male. Why do I feel that way? And if I’m right, then why are there sex categories?</p>
<p>Consider the histogram of marathon run times shown in Figure <a href="differences-in-athletics.html#fig:marathon-times">14.3</a>. The plot uses transparent colors again to show two distributions, one for males and one for females.</p>
<div class="figure" style="text-align: center"><span id="fig:marathon-times"></span>
<img src="carpedatum_files/figure-html/marathon-times-1.png" alt="2017 Boston Marathon finishing times" width="90%" />
<p class="caption">
Figure 14.3: 2017 Boston Marathon finishing times
</p>
</div>
<p>A couple of things to notice. For one thing, there is a large overlap in the two distributions. This means that there are a lot of males and females who can be matched up with similar finishing times. This observation agrees with my intution that as a below-average runner, my competitive odds against males and females may not be so different. However, there is also clearly a shift in the means of the distributions. The males are finishing faster on average. In particular, at the left end of the distribution, we are looking at the elite marathoners. Let’s zoom in on that part of the distribution.</p>
<div class="figure" style="text-align: center"><span id="fig:marathon-fast"></span>
<img src="carpedatum_files/figure-html/marathon-fast-1.png" alt="Fastest Runners in the 2017 Boston Marathon" width="90%" />
<p class="caption">
Figure 14.4: Fastest Runners in the 2017 Boston Marathon
</p>
</div>
<p>Among the elite athletes who complete the maraton in under two hours and forty minutes, the males are clearly dominant. And the top 20 finishers are all male. In such a competition, it doesn’t look like a female runner will ever win.</p>
<p>We’ve created an interactive simulation for you to explore this idea further. In the simulation, you can vary the mean difference between two similar distributions and observe how often a random match-up between one member from each group (males/females) wins, and how often one of the slower group members places in the top 10.</p>
<p>As we can all imagine, dividing competitive running (and other sports) into separate events for males and females was designed to make the competition more interesting for the female athletes. There is still only so much room at the top. But under separate competition, the top few places for female athletes are accessible to female athletes.</p>
<p>Many societies now recognize that biology and gender do not align perfectly. A person whose sex at birth was male may at some point grow up to identify as a woman. This person may undergo sex reassignment or not. They may use hormone therapy. To add to the complexity, we now understand that there are sometimes differences in sex development. Trans and non-binary athletes may not fit the two-category mold that competitive sports organizations created. But there are non-cis-gendered women who want to be allowed to compete in the “women’s” category. Is it it fair to exclude trans women from doing so? Is it fair to them? Is it fair to their cis-gendered female competitors to include anyone who identifies as a woman? Data science cannot answer this question for us, but a cold look at the data can help us at least quantify the effects of these decisions.</p>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="11">
<li id="fn11"><p>The answer is D. Here’s why you need each quantity. <strong>Sample means.</strong> Clearly, if the sample means are very close, you are more likely to accept the possibility that the difference occurred by chance than if they are very different, so sample means are necessary. On the heels of that, the notion of “close” values of the means is itself dependent on the range of values we expect (i.e., on the <strong>variance</strong> or spread). Two buildings are close in height if one is 271 ft tall and another is 274 ft tall. But a difference of 3 feet among human beings is enormous. It’s enormous <em>relative</em> to the standard deviation, which for adult human beings is about 4 inches. The standard deviation for building heights is over 200 ft if we include skyscrapers. Finally, the <strong>sample size.</strong> The law of large numbers tells us that the sample mean gets closer to the population mean as the sample size increases. However, when the sample size is small, we will have more sampling variance. Intuitively, we can think about it this way: Let’s suppose the distributions are different but not so different that they don’t overlap. If we sample only two people from each population, we may get two tall people by chance from one (or short ones from the other) in such a way that the means are close by chance. But if we have small differences in means with large samples (say, 1000), then we believe that the means are, in fact, close or even equal.<a href="differences-in-athletics.html#fnref11" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="is-the-system-fair.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="nyc-covid-19-data.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": null,
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
