<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 15 NYC COVID-19 Data | Carpe Datum</title>
  <meta name="description" content="Chapter 15 NYC COVID-19 Data | Carpe Datum" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 15 NYC COVID-19 Data | Carpe Datum" />
  <meta property="og:type" content="book" />
  
  
  
  <meta name="github-repo" content="ybergner/carpe-datum" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 15 NYC COVID-19 Data | Carpe Datum" />
  
  
  

<meta name="author" content="Yoav Bergner" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="differences-in-athletics.html"/>
<link rel="next" href="sec-randomness.html"/>
<script src="libs/header-attrs-2.7/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Carpe Datum: Data Science for Life's Big Questions</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#caveat"><i class="fa fa-check"></i>Caveat</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#guiding-principles-in-this-book"><i class="fa fa-check"></i>Guiding principles in this book</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#question-driven"><i class="fa fa-check"></i>Question-driven</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#no-proofs"><i class="fa fa-check"></i>No proofs</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="how-many-kinds-of-people-are-there.html"><a href="how-many-kinds-of-people-are-there.html"><i class="fa fa-check"></i>How Many Kinds of People Are There?</a>
<ul>
<li class="chapter" data-level="" data-path="how-many-kinds-of-people-are-there.html"><a href="how-many-kinds-of-people-are-there.html#things-are-about-to-get-meta-right-from-the-start"><i class="fa fa-check"></i>Things are about to get meta right from the start</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="categories.html"><a href="categories.html"><i class="fa fa-check"></i><b>1</b> Categories, counts, and kinds</a>
<ul>
<li class="chapter" data-level="" data-path="categories.html"><a href="categories.html#two-kinds-of-people"><i class="fa fa-check"></i>Two Kinds of People</a></li>
<li class="chapter" data-level="" data-path="categories.html"><a href="categories.html#samples-and-populations-a-statistical-caveat"><i class="fa fa-check"></i>Samples and Populations: A Statistical Caveat</a></li>
<li class="chapter" data-level="" data-path="categories.html"><a href="categories.html#a-psychological-caveat"><i class="fa fa-check"></i>A Psychological Caveat</a></li>
<li class="chapter" data-level="" data-path="categories.html"><a href="categories.html#summarizing-data"><i class="fa fa-check"></i>Summarizing data</a></li>
<li class="chapter" data-level="" data-path="categories.html"><a href="categories.html#checkpoint"><i class="fa fa-check"></i>Checkpoint</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="dimensions.html"><a href="dimensions.html"><i class="fa fa-check"></i><b>2</b> Dimensions</a>
<ul>
<li class="chapter" data-level="" data-path="dimensions.html"><a href="dimensions.html#independence-association-and-contingency"><i class="fa fa-check"></i>Independence, Association, and Contingency</a></li>
<li class="chapter" data-level="" data-path="dimensions.html"><a href="dimensions.html#latent-factors-and-measurement"><i class="fa fa-check"></i>Latent Factors and Measurement</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="test-indep.html"><a href="test-indep.html"><i class="fa fa-check"></i><b>3</b> Tests of independence: A first look starring alternate universes</a>
<ul>
<li class="chapter" data-level="" data-path="test-indep.html"><a href="test-indep.html#rise-of-the-machines"><i class="fa fa-check"></i>Rise of the machines</a></li>
<li class="chapter" data-level="" data-path="test-indep.html"><a href="test-indep.html#hypothesis-testing-just-happened"><i class="fa fa-check"></i>Hypothesis testing just happened</a></li>
<li class="chapter" data-level="" data-path="test-indep.html"><a href="test-indep.html#caveats"><i class="fa fa-check"></i>Caveats</a></li>
<li class="chapter" data-level="" data-path="test-indep.html"><a href="test-indep.html#sampling-simulations-and-randomness"><i class="fa fa-check"></i>Sampling, simulations, and randomness</a>
<ul>
<li class="chapter" data-level="" data-path="test-indep.html"><a href="test-indep.html#tossing-virtual-coins"><i class="fa fa-check"></i>Tossing (virtual) coins</a></li>
<li><a href="test-indep.html#but-some-observations-do-occur-more-than-others">But some observations <em>do</em> occur more than others</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="test-indep.html"><a href="test-indep.html#recap"><i class="fa fa-check"></i>Recap</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="shades.html"><a href="shades.html"><i class="fa fa-check"></i><b>4</b> (An Infinite Number of) Shades of Gray (or Brown)</a>
<ul>
<li class="chapter" data-level="" data-path="shades.html"><a href="shades.html#poopiness"><i class="fa fa-check"></i>Poopiness</a>
<ul>
<li class="chapter" data-level="" data-path="shades.html"><a href="shades.html#mixtures"><i class="fa fa-check"></i>Mixtures</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="shades.html"><a href="shades.html#crappiness"><i class="fa fa-check"></i>Crappiness</a>
<ul>
<li class="chapter" data-level="" data-path="shades.html"><a href="shades.html#check-your-understanding"><i class="fa fa-check"></i>Check your understanding</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="cut-scores-and-abnormality.html"><a href="cut-scores-and-abnormality.html"><i class="fa fa-check"></i><b>5</b> Cut Scores and Abnormality</a></li>
<li class="chapter" data-level="6" data-path="the-modal-american.html"><a href="the-modal-american.html"><i class="fa fa-check"></i><b>6</b> The Modal American</a>
<ul>
<li class="chapter" data-level="" data-path="the-modal-american.html"><a href="the-modal-american.html#step-one-categories"><i class="fa fa-check"></i>Step one: categories</a></li>
<li class="chapter" data-level="" data-path="the-modal-american.html"><a href="the-modal-american.html#step-two-contingency-table"><i class="fa fa-check"></i>Step two: contingency table</a></li>
<li class="chapter" data-level="" data-path="the-modal-american.html"><a href="the-modal-american.html#exercises"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="sixteen-personalities-or-five-factors.html"><a href="sixteen-personalities-or-five-factors.html"><i class="fa fa-check"></i><b>7</b> Sixteen Personalities or Five Factors?</a>
<ul>
<li class="chapter" data-level="" data-path="sixteen-personalities-or-five-factors.html"><a href="sixteen-personalities-or-five-factors.html#mbti"><i class="fa fa-check"></i>MBTI</a></li>
<li class="chapter" data-level="" data-path="sixteen-personalities-or-five-factors.html"><a href="sixteen-personalities-or-five-factors.html#big-five"><i class="fa fa-check"></i>Big Five</a></li>
<li class="chapter" data-level="" data-path="sixteen-personalities-or-five-factors.html"><a href="sixteen-personalities-or-five-factors.html#twenty-questions-about-extraversion"><i class="fa fa-check"></i>Twenty Questions (about Extraversion)</a></li>
<li class="chapter" data-level="" data-path="sixteen-personalities-or-five-factors.html"><a href="sixteen-personalities-or-five-factors.html#but-whats-the-point"><i class="fa fa-check"></i>But what’s the point?</a></li>
<li class="chapter" data-level="" data-path="sixteen-personalities-or-five-factors.html"><a href="sixteen-personalities-or-five-factors.html#recap-1"><i class="fa fa-check"></i>Recap</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="when-and-how-will-you-die.html"><a href="when-and-how-will-you-die.html"><i class="fa fa-check"></i><b>8</b> When and How Will You Die?</a>
<ul>
<li class="chapter" data-level="" data-path="when-and-how-will-you-die.html"><a href="when-and-how-will-you-die.html#not-quite-death-but-um-rain"><i class="fa fa-check"></i>Not Quite Death, but, um… Rain?</a>
<ul>
<li class="chapter" data-level="" data-path="when-and-how-will-you-die.html"><a href="when-and-how-will-you-die.html#stochastic-vs-deterministic-relationships"><i class="fa fa-check"></i>Stochastic vs Deterministic relationships</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="when-and-how-will-you-die.html"><a href="when-and-how-will-you-die.html#ways-of-thinking-about-probabilistic-statements"><i class="fa fa-check"></i>Ways of thinking about probabilistic statements</a>
<ul>
<li class="chapter" data-level="" data-path="when-and-how-will-you-die.html"><a href="when-and-how-will-you-die.html#ensembles"><i class="fa fa-check"></i>Ensembles</a></li>
<li class="chapter" data-level="" data-path="when-and-how-will-you-die.html"><a href="when-and-how-will-you-die.html#degree-of-belief"><i class="fa fa-check"></i>Degree of belief</a></li>
<li class="chapter" data-level="" data-path="when-and-how-will-you-die.html"><a href="when-and-how-will-you-die.html#decisions"><i class="fa fa-check"></i>Decisions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="when-and-how-will-you-die.html"><a href="when-and-how-will-you-die.html#death"><i class="fa fa-check"></i>Death</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="conditional-death.html"><a href="conditional-death.html"><i class="fa fa-check"></i><b>9</b> Conditional Death</a>
<ul>
<li class="chapter" data-level="" data-path="conditional-death.html"><a href="conditional-death.html#how-does-the-death-simulation-work"><i class="fa fa-check"></i>How does the death (simulation) work?</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="somefacts.html"><a href="somefacts.html"><i class="fa fa-check"></i><b>10</b> Some facts about Probabilities</a>
<ul>
<li class="chapter" data-level="" data-path="somefacts.html"><a href="somefacts.html#conditional-probabilities"><i class="fa fa-check"></i>Conditional Probabilities</a></li>
<li class="chapter" data-level="" data-path="somefacts.html"><a href="somefacts.html#conditional-death-again"><i class="fa fa-check"></i>Conditional death, again</a>
<ul>
<li class="chapter" data-level="" data-path="somefacts.html"><a href="somefacts.html#just-to-make-things-weird"><i class="fa fa-check"></i>Just to make things weird</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="how-you-will-die-causes-or-conditions.html"><a href="how-you-will-die-causes-or-conditions.html"><i class="fa fa-check"></i><b>11</b> How You Will Die: Causes or Conditions?</a>
<ul>
<li class="chapter" data-level="" data-path="how-you-will-die-causes-or-conditions.html"><a href="how-you-will-die-causes-or-conditions.html#causes-of-death-colloquially"><i class="fa fa-check"></i>Causes of death, colloquially</a></li>
<li class="chapter" data-level="" data-path="how-you-will-die-causes-or-conditions.html"><a href="how-you-will-die-causes-or-conditions.html#hold-my-beer"><i class="fa fa-check"></i>Hold my beer</a></li>
<li class="chapter" data-level="" data-path="how-you-will-die-causes-or-conditions.html"><a href="how-you-will-die-causes-or-conditions.html#non-deterministic-causation"><i class="fa fa-check"></i>Non-deterministic Causation</a></li>
<li class="chapter" data-level="" data-path="how-you-will-die-causes-or-conditions.html"><a href="how-you-will-die-causes-or-conditions.html#testing-for-an-association-between-two-variables"><i class="fa fa-check"></i>Testing for an association between two variables</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="will-you-make-money.html"><a href="will-you-make-money.html"><i class="fa fa-check"></i>Will You Make Money?</a>
<ul>
<li class="chapter" data-level="" data-path="will-you-make-money.html"><a href="will-you-make-money.html#battle-of-the-bills"><i class="fa fa-check"></i>Battle of the Bills</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="betting-on-beer-or-ice-cream.html"><a href="betting-on-beer-or-ice-cream.html"><i class="fa fa-check"></i><b>12</b> Betting on Beer (or Ice Cream)</a>
<ul>
<li class="chapter" data-level="" data-path="betting-on-beer-or-ice-cream.html"><a href="betting-on-beer-or-ice-cream.html#how-do-statisticians-solve-problems-like-this"><i class="fa fa-check"></i>How do statisticians solve problems like this?</a>
<ul>
<li class="chapter" data-level="" data-path="betting-on-beer-or-ice-cream.html"><a href="betting-on-beer-or-ice-cream.html#the-solution-by-counting-or-combinatorics"><i class="fa fa-check"></i>The solution by counting, or combinatorics</a></li>
<li class="chapter" data-level="" data-path="betting-on-beer-or-ice-cream.html"><a href="betting-on-beer-or-ice-cream.html#the-solution-by-distribution-or-statistics"><i class="fa fa-check"></i>The solution by distribution, or statistics</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="expected-value.html"><a href="expected-value.html"><i class="fa fa-check"></i><b>13</b> Expected Value</a>
<ul>
<li class="chapter" data-level="" data-path="expected-value.html"><a href="expected-value.html#betting-on-ice-cream"><i class="fa fa-check"></i>Betting on ice cream</a>
<ul>
<li class="chapter" data-level="" data-path="expected-value.html"><a href="expected-value.html#by-the-statistical-power-of-grayskull"><i class="fa fa-check"></i>By the (Statistical) Power of Grayskull</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="expected-value.html"><a href="expected-value.html#betting-on-your-future"><i class="fa fa-check"></i>Betting on your Future</a>
<ul>
<li class="chapter" data-level="" data-path="expected-value.html"><a href="expected-value.html#why-why-why-multiply-ay-ay"><i class="fa fa-check"></i>Why why why multiply-ay-ay?</a></li>
<li class="chapter" data-level="" data-path="expected-value.html"><a href="expected-value.html#where-do-branching-probabilities-come-from"><i class="fa fa-check"></i>Where do branching probabilities come from?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="is-the-system-fair.html"><a href="is-the-system-fair.html"><i class="fa fa-check"></i>Is the System Fair?</a></li>
<li class="chapter" data-level="14" data-path="differences-in-athletics.html"><a href="differences-in-athletics.html"><i class="fa fa-check"></i><b>14</b> Differences in athletics</a>
<ul>
<li class="chapter" data-level="" data-path="differences-in-athletics.html"><a href="differences-in-athletics.html#are-professional-basketball-players-taller"><i class="fa fa-check"></i>Are professional basketball players taller?</a>
<ul>
<li class="chapter" data-level="" data-path="differences-in-athletics.html"><a href="differences-in-athletics.html#none-of-this-is-surprising"><i class="fa fa-check"></i>None of this is surprising</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="differences-in-athletics.html"><a href="differences-in-athletics.html#surprising-differences"><i class="fa fa-check"></i>Surprising differences</a></li>
<li class="chapter" data-level="" data-path="differences-in-athletics.html"><a href="differences-in-athletics.html#fairness-on-trial-trans-athletes"><i class="fa fa-check"></i>Fairness on trial: trans athletes</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="nyc-covid-19-data.html"><a href="nyc-covid-19-data.html"><i class="fa fa-check"></i><b>15</b> NYC COVID-19 Data</a>
<ul>
<li class="chapter" data-level="" data-path="nyc-covid-19-data.html"><a href="nyc-covid-19-data.html#prologue"><i class="fa fa-check"></i>Prologue</a></li>
<li class="chapter" data-level="15.1" data-path="nyc-covid-19-data.html"><a href="nyc-covid-19-data.html#part1"><i class="fa fa-check"></i><b>15.1</b> COVID NYC</a>
<ul>
<li class="chapter" data-level="" data-path="nyc-covid-19-data.html"><a href="nyc-covid-19-data.html#getting-some-data"><i class="fa fa-check"></i>Getting some data</a></li>
<li class="chapter" data-level="" data-path="nyc-covid-19-data.html"><a href="nyc-covid-19-data.html#local-data-on-covid-from-the-city-andor-state"><i class="fa fa-check"></i>Local data on COVID from the city and/or state</a></li>
</ul></li>
<li class="chapter" data-level="15.2" data-path="nyc-covid-19-data.html"><a href="nyc-covid-19-data.html#part2"><i class="fa fa-check"></i><b>15.2</b> Getting started with US Census data</a>
<ul>
<li class="chapter" data-level="" data-path="nyc-covid-19-data.html"><a href="nyc-covid-19-data.html#census-variables"><i class="fa fa-check"></i>Census Variables</a></li>
<li class="chapter" data-level="" data-path="nyc-covid-19-data.html"><a href="nyc-covid-19-data.html#geography-units"><i class="fa fa-check"></i>Geography Units</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="nyc-covid-19-data.html"><a href="nyc-covid-19-data.html#part3"><i class="fa fa-check"></i><b>15.3</b> More (and messier) Census data</a>
<ul>
<li class="chapter" data-level="" data-path="nyc-covid-19-data.html"><a href="nyc-covid-19-data.html#exploring-the-acs-data"><i class="fa fa-check"></i>Exploring the ACS data</a></li>
</ul></li>
<li class="chapter" data-level="15.4" data-path="nyc-covid-19-data.html"><a href="nyc-covid-19-data.html#zipcode"><i class="fa fa-check"></i><b>15.4</b> Zipcode tabulation area</a>
<ul>
<li class="chapter" data-level="" data-path="nyc-covid-19-data.html"><a href="nyc-covid-19-data.html#some-more-variables-to-play-with"><i class="fa fa-check"></i>Some more variables to play with</a></li>
</ul></li>
<li class="chapter" data-level="15.5" data-path="nyc-covid-19-data.html"><a href="nyc-covid-19-data.html#mapviz"><i class="fa fa-check"></i><b>15.5</b> Visualizing data on maps</a>
<ul>
<li class="chapter" data-level="" data-path="nyc-covid-19-data.html"><a href="nyc-covid-19-data.html#shapefiles"><i class="fa fa-check"></i>Shapefiles</a></li>
<li class="chapter" data-level="" data-path="nyc-covid-19-data.html"><a href="nyc-covid-19-data.html#coloring-in-the-shapes"><i class="fa fa-check"></i>Coloring in the shapes</a></li>
<li class="chapter" data-level="" data-path="nyc-covid-19-data.html"><a href="nyc-covid-19-data.html#scatterplots"><i class="fa fa-check"></i>Scatterplots</a></li>
</ul></li>
</ul></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="sec-randomness.html"><a href="sec-randomness.html"><i class="fa fa-check"></i><b>A</b> Randomness</a>
<ul>
<li class="chapter" data-level="A.1" data-path="sec-randomness.html"><a href="sec-randomness.html#defining-random-processes"><i class="fa fa-check"></i><b>A.1</b> Defining random processes</a></li>
<li class="chapter" data-level="A.2" data-path="sec-randomness.html"><a href="sec-randomness.html#predictions-about-random-events"><i class="fa fa-check"></i><b>A.2</b> Predictions about random events</a></li>
<li class="chapter" data-level="A.3" data-path="sec-randomness.html"><a href="sec-randomness.html#modification-for-continuous-observations"><i class="fa fa-check"></i><b>A.3</b> Modification for continuous observations</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Carpe Datum</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="nyc-covid-19-data" class="section level1" number="15">
<h1><span class="header-section-number">Chapter 15</span> NYC COVID-19 Data</h1>
<div id="prologue" class="section level2 unnumbered">
<h2>Prologue</h2>
<p>Although Madonna may have called COVID-19 <a href="https://pagesix.com/2020/03/22/madonna-calls-coronavirus-the-great-equalizer-in-bizarre-bathtub-video/" target="_blank">the great equalizer</a> during the early stages of the outbreak in the US, others quickly highlighted some data that suggested the opposite might be true. Whenever we acknowledge the range of human experience, in the case of disease as in other cases, variance in outcomes does not necessarily imply systematic unfairness. For example, if COVID-19 is more fatal for elderly adults, as it appears to be, this is not something we would label as obviously unfair. Everyone gets old, and physical deterioration unfortunately comes with the territory. Certain chronic health conditions make people more vulnerable to COVID-19, but some of those conditions might just be the result of bad luck. We can try to make a world in which everyone has comparable access to healthcare, but we probably still can’t make a world in which everyone has the same health outcomes.</p>
<p>However, consider the following headlines:</p>
<ul>
<li><p><a href="https://www.sciencenews.org/article/coronavirus-why-african-americans-vulnerable-covid-19-health-race" target="_blank">Why African-Americans may be especially vulnerable to COVID-19</a></p></li>
<li><p><a href="https://theintercept.com/2020/04/09/nyc-coronavirus-deaths-race-economic-divide/" target="_blank">Coronavirus Numbers Reflect New York City’s Deep Economic Divide</a></p></li>
<li><p><a href="https://abcnews.go.com/Health/nyc-stark-contrast-covid-19-infection-rates-based/story?id=69920706" target="_blank">In NYC, ‘stark contrast’ in COVID-19 infection rates based on education and race</a></p></li>
<li><p><a href="https://www.statnews.com/2020/04/09/hospitalized-covid-19-patients-differences-by-race-and-sex/" target="_blank">Who gets hospitalized for Covid-19? Report shows differences by race and sex</a></p></li>
</ul>
<p>When adverse health outcomes are associated with income, race, and/or sex, we are much more likely to cry foul than when they are associated with age or pre-existing chronic conditions. Part of this has to do with the difference between variance among individuals, which is an unavoidable fact of life, and variance between certain classes or groups. These media reports are all suggesting that COVID-19 may not be affecting all groups with the same severity. What exactly does that mean, and is it evidence of unfairness?</p>
<p>New York City emerged early as the epicenter of the US outbreak, claiming over 14,000 lives by late April 2020. As specific data have became available, researchers and reporters examined counts of coronavirus infections and/or deaths by zip code and borough, by age, sex, and race. In this chapter, we will take a closer look at the data and the media reports.</p>
<p>Some additional reports on Coronavirus in New York:</p>
<ul>
<li><a href="https://furmancenter.org/thestoop/entry/covid-19-cases-in-new-york-city-a-neighborhood-level-analysis" target="_blank">COVID-19 Cases in New York City, a Neighborhood-Level Analysis</a></li>
<li><a href="https://gothamist.com/news/coronavirus-statistics-tracking-epidemic-new-york" target="_blank">Coronavirus Statistics: Tracking The Epidemic In New York</a></li>
</ul>
<p>There are a bunch of sites that let you engage interactively with COVID-19 data. The purpose of this chapter is to show you how to build your own resource.</p>
</div>
<div id="part1" class="section level2" number="15.1">
<h2><span class="header-section-number">15.1</span> COVID NYC</h2>
<p>On April 10, 2020, <a href="https://abcnews.go.com/Health/nyc-stark-contrast-covid-19-infection-rates-based/story?id=69920706" target="_blank">ABC News</a> covered an online report (by the NYU Furman Center) that examined cases of COVID-19 in New York City on a neighborhood level. Most COVID-19 data that had been coming out had been reporting on the city as a whole. The main idea here was that neighborhoods tell a different story. Data scientists call this a shift in the unit-of-analysis. The city is made of boroughs, which themselves are made up of smaller neighborhoods. So the unit of analysis could be the whole city, the boroughs of the city, or something even more fine-grained, like neighborhoods or zipcode areas. For example, some zipcodes are wealthier and some poorer. Zipcode areas also vary by racial composition. If we examine COVID-19 outcomes by neighborhood, we may be able to see patterns and associations between disease incidence and race or socio-economic variables. Indeed, the Furman Center found such associations. The ABC News report produced images like the following:</p>
<p><img src="images/abc_COVID19NycZip_v03_KA_hpEmbed_17x12_992.jpg" /></p>
<p>People familiar with the layout of New York City might be able to identify low-income and largely African-American neighborhoods like Hunts Point in the South Bronx. ABC News produced a corresponding map showing the share of adults with college degree, a measure of educational attainment which the Furman Center report said was associated with disease incidence.</p>
<p><img src="images/abc_CollegeDegreeNycZip_v02_KA_hpEmbed_17x12_992.jpg" /></p>
<p>It requires switching back and forth between these images, but the dark regions on the COVID map (higher rates of disease) seem to often correspond to the lighter regions on the college degree map (lower college share). In other words, areas with lower educational attainment seem to have higher rates of the disease. There are many possible explanations of this relationship, which are discussed in the Furman report and elsewhere.</p>
<p>How does one make these data visualizations? And are they the best way to “see” the signals in the data?</p>
<p>ABC News also reproduced a version of table below, showing racial composition by neighborhood. The title may confuse matters, however. In this table, multiple neighborhoods (zipcodes) are actually grouped together into five sets using <strong>quintiles.</strong> You take all of the zipcodes, rank-order them by COVID-19 concentration, and then select the bottom fifth, the next fifth, and so on up to the top fifth. These groups are labeled “lowest concentration,” “low concentration,” and so on up to “highest concentration.”</p>
<p>To make matters confusing, the word “quintile” is often used referring to the five sets (for example, “the lower quintile”). But strictly speaking, the quintiles are actually the cut-points. So for five groups, there are four quintiles. If you look at the table below, the cut-points/quintiles are {3.33, 4.13, 4.77, 5.87}. Of course, this division process can be done for a different number of <strong>quantiles</strong>–note the spelling–not necessarily five. A division of three groups is made by choosing two (cut-point) tertiles or terciles. The median is the 2-quantile, as it is the cut-point that divides a data set into two equal parts. Unfortunately, the naming conventions here are rather confusing, but you get used to them if you use them a lot.</p>
<p><img src="images/abc_COVID19RacialComp_v02_KA_hpEmbed_37x16_992.jpg" /></p>
<p>If you look at the table above, you may notice trends or patterns between racial composition (of these groups of neighborhoods) and COVID-19 concentration. The trends are not perfectly linear. But, for example, the proportion of Black and Hispanic people in the low-concentration neighborhoods is 37.3%. While in the high concentration neighborhoods, this combined share is 55.6%.</p>
<p>In the remainder of this tutorial, we will examine how to recreate graphs and tables like the one above from publicly available data. This will enable you to create your own versions or update the ones above with new data. We will also look at alternative representations and at some simulation-based tests to see how likely it is that such disparities might occur by chance.</p>
<p>Let’s begin!</p>
<div id="getting-some-data" class="section level3 unnumbered">
<h3>Getting some data</h3>
<p>In this tutorial, I will walk you through the steps of creating some of the figures and tables that go into media reports about COVID-19 outcomes. The examples here are all NYC-centric, but the methods, especially for US Census data, are completely general. The hardest part of all of this–and this is generally true about the practice of data science–is getting all of the data from different sources cleaned up and fitted together.</p>
</div>
<div id="local-data-on-covid-from-the-city-andor-state" class="section level3 unnumbered">
<h3>Local data on COVID from the city and/or state</h3>
<p>For state and municipality-level COVID-19 data in New York, these are some sources:</p>
<ul>
<li><a href="https://www1.nyc.gov/site/doh/covid/covid-19-data-archive.page" target="_blank">NYC data summaries</a></li>
<li><a href="https://github.com/nychealth/coronavirus-data" target="_blank">NYC Health GitHub</a></li>
<li><a href="https://health.data.ny.gov/Health/New-York-State-Statewide-COVID-19-Testing/xdss-u53e" target="_blank">NY Statewide data</a></li>
</ul>
<p>These sources have been updated daily (as of April 2021, still going). I will be working with the GitHub data as of April 23, 2020. This was early in the pandemic, just as the first big wave that hit New York City was beginning to subside. This date was about two weeks later than the Furman/ABC reports linked above. I downloaded the files from the online repository and put them into a folder on my computer. (As of April 2021, the NYC DOH data repository includes more tables, such as tabulations by race and poverty; however, these were not available in the beginning. So this information had to come from other sources. We’ll get into that below, because it is widely useful.)</p>
<p>For starters, here I will load and view the borough-level data table.</p>
<pre><code>##   BOROUGH_GROUP COVID_CASE_COUNT COVID_CASE_RATE
## 1     The Bronx            28875         1962.05
## 2      Brooklyn            34476         1269.58
## 3     Manhattan            16754          887.36
## 4        Queens            39856         1589.55
## 5 Staten Island             9755         1944.40
## 6      Citywide           129788              NA</code></pre>
<p>According to the documentation in the GitHub README file (a valuable source of information), this table contains rates of confirmed cases, by NYC borough of residence. Rates are:</p>
<ul>
<li>Cumulative since the start of the outbreak</li>
<li>Age adjusted according to <a href="https://www.cdc.gov/nchs/data/statnt/statnt20.pdf" target="_blank">the US 2000 standard population</a></li>
<li>Per 100,000 people in the borough</li>
</ul>
<p>What does age-adjusted rate mean? You can read the link, but the main idea here is to try to put all of the boroughs on equal footing in the rate per 100,000 people, even if some boroughs have an older or younger population than others. Which it turns out they do. Later, once we have borough populations, we could examine simple population-adjusted rates that are not age-adjusted and see what those look like in comparison.</p>
<p>If we wanted to do age-adjustment, or even simpler population adjustment, we would need to supplement this COVID data with population data, for example obtained from the US Census. Before we turn to that, let us just quickly explore the other data provided by NYC.</p>
<pre><code>##        SEX_GROUP COVID_CASE_RATE HOSPITALIZED_CASE_RATE DEATH_RATE
## 1         Female         1394.88                 324.21      77.38
## 2           Male         1702.93                 507.52     134.42
## 3 Citywide total         1545.33                 411.99     104.91</code></pre>
<p>(By the way, you may get a warning like, “incomplete final line found” when reading this file. You can ignore it. R is expecting each line in a .csv file to end with a newline/return. You can also just open the file and add that newline after the last row if you like).</p>
<p>Case and fatality rates by sex show that males are being infected and dying at significantly higher rates. Note that each of these is already adjusted to rate per 100,000.</p>
<pre><code>##            AGE_GROUP COVID_CASE_RATE HOSPITALIZED_CASE_RATE DEATH_RATE
## 1         0-17 years          149.86                  12.91       0.17
## 2        18-44 years         1429.09                 147.79      11.28
## 3        45-64 years         2305.73                 600.33      96.69
## 4        65-74 years         2351.39                1123.27     311.68
## 5 75 and older years         2728.10                1682.16     778.83
## 6     Citywide total         1545.33                 411.99     104.91</code></pre>
<p>Age-level data show a few interesting features. For one, children are barely even getting infected. Among adults, infection rates are slightly higher for older adults, but death rates are much higher. We could derive a measure of case fatality rate (CFR) as follows:</p>
<pre><code>##            AGE_GROUP COVID_CASE_RATE HOSPITALIZED_CASE_RATE DEATH_RATE   CFR
## 1         0-17 years          149.86                  12.91       0.17 0.001
## 2        18-44 years         1429.09                 147.79      11.28 0.008
## 3        45-64 years         2305.73                 600.33      96.69 0.042
## 4        65-74 years         2351.39                1123.27     311.68 0.133
## 5 75 and older years         2728.10                1682.16     778.83 0.285
## 6     Citywide total         1545.33                 411.99     104.91 0.068</code></pre>
<p>From this we see that adults 75 and older have a 28.5% chance of dying from COVID-19, compared to a 4.2% for adults between 45-64.</p>
<p><strong>Exercise</strong>: compute the case fatality rate by sex.</p>
<p>Since I’m going to be using this method later, there is another way to add a new CFR variable to the table using the <code>mutate</code> function in the <code>dplyr</code> package. It looks slightly more complicated, but it has benefits which I won’t get into now. The important thing here is just to recognize that there are different ways of achieving the same ends.</p>
<pre><code>##            AGE_GROUP COVID_CASE_RATE HOSPITALIZED_CASE_RATE DEATH_RATE   CFR
## 1         0-17 years          149.86                  12.91       0.17 0.001
## 2        18-44 years         1429.09                 147.79      11.28 0.008
## 3        45-64 years         2305.73                 600.33      96.69 0.042
## 4        65-74 years         2351.39                1123.27     311.68 0.133
## 5 75 and older years         2728.10                1682.16     778.83 0.285
## 6     Citywide total         1545.33                 411.99     104.91 0.068</code></pre>
<p>The most captivating data set provided by the city (hence the images we started out with) is probably the zipcode-level data, the first few rows of which look like this:</p>
<pre><code>##    MODZCTA Positive Total zcta_cum.perc_pos
## 1       NA     1864  2078             89.70
## 2    10001      260   571             45.53
## 3    10002      712  1358             52.43
## 4    10003      347   830             41.81
## 5    10004       24    64             37.50
## 6    10005       44   137             32.12
## 7    10006       14    54             25.93
## 8    10007       40   130             30.77
## 9    10009      518  1180             43.90
## 10   10010      201   561             35.83
## 11   10011      394   852             46.24
## 12   10012      116   330             35.15
## 13   10013      179   426             42.02
## 14   10014      233   529             44.05
## 15   10016      502  1197             41.94
## 16   10017      107   310             34.52
## 17   10018      168   375             44.80
## 18   10019      441   999             44.14
## 19   10021      431  1148             37.54
## 20   10022      250   668             37.43</code></pre>
<p>Notice that the first row is missing a zipcode. Presumably these are COVID tests for which we do not know where the people who were tested actually reside.</p>
<p>For each other row, we have a zipcode, the number of positive tests, the number of total tests, and the percent positive.</p>
<p><strong>Exercise</strong>: Which of these expressions should give the percent positive tests?</p>
<pre><code>nyc_zipcode_data$Total/nyc_zipcode_data$Positive*100
nyc_zipcode_data$Positive/nyc_zipcode_data$Total
nyc_zipcode_data$Positive/nyc_zipcode_data$Total*100
(nyc_zipcode_data$Total-nyc_zipcode_data$Positive)
(nyc_zipcode_data$Total-nyc_zipcode_data$Positive)*100</code></pre>
<p>Now you might want to keep the first row, the one with the missing zipcode, in your data. But I would rather remove it now, because I’m going to try to add information to this zipcode table down the line. While I’m at it, I will also rename the column “MODZCTA” with “zipcode.”</p>
<pre><code>##   zipcode Positive Total zcta_cum.perc_pos
## 2   10001      260   571             45.53
## 3   10002      712  1358             52.43
## 4   10003      347   830             41.81
## 5   10004       24    64             37.50
## 6   10005       44   137             32.12
## 7   10006       14    54             25.93</code></pre>
<p>There are a couple more tables included in the GitHub repository, for example ones showing the daily tracking of new cases, hospitalizations, and deaths. But as we are focusing on the neighborhood level counts, I will leave them out of these notes.</p>
<p>In the next part of the series, we will get started with US Census data.</p>
</div>
</div>
<div id="part2" class="section level2" number="15.2">
<h2><span class="header-section-number">15.2</span> Getting started with US Census data</h2>
<p>To get census data, you can go to (<a href="https://data.census.gov/" class="uri">https://data.census.gov/</a>), but be warned: it is a big maze and not that easy to navigate. What the pros who make media reports do (probably) is use the US Census API to make specific requests for data. If you use it a lot, you will need an API key. This is easy enough to get, but you need to <a href="https://api.census.gov/data/key_signup.html" target="_blank">request one here</a>. Once you have a key, you can declare it in your R code or, better for security/code-sharing, embed it in a .Renviron file.</p>
<p>Here I will load the <code>censusapi</code> package (and also <code>dplyr</code> while I’m at it), and load my key. You can modify this line with your key. If you don’t have one, some or all of the code below will still work if you comment out the <code>key=myKey</code>. Without an API key, however, there is a limit to the size and number of queries per IP address.</p>
<p>More importantly, when it comes to census data, you need to know what you’re asking for. That means you need to know which data sets, which variables, which geographic units, etc. A brief introductory <a href="https://www.census.gov/content/dam/Census/data/developers/api-user-guide/api-guide.pdf" target="_blank">API users guide can be found here</a>. It’s 20 pages long. You can just follow along here if you want some examples.</p>
<p>We will be interested in the <a href="https://www.census.gov/data/developers/data-sets/acs-5year.html" target="_blank">American Community Survey 5-Year data</a> (aka ACS5) which provides estimates aggregated over a 5-year period, revisited every two years. The last published data set, i.e., the most current one available, is from 2018.</p>
<div id="census-variables" class="section level3 unnumbered">
<h3>Census Variables</h3>
<p>There are something like 20,000 variables available in ACS, and these can be retrieved through queries invidividually or in groups. Some useful groups for our analysis are the following</p>
<ul>
<li>B01001 SEX BY AGE
<ul>
<li>This has a lot of subcategories, such as Male 5-9 Years, Male 10-14 years, etc.</li>
</ul></li>
<li>B02001 RACE (disregards Hispanic or Latino Origin)</li>
<li>B03002 HISPANIC OR LATINO ORIGIN BY RACE<br />
</li>
<li>B19013 MEDIAN HOUSEHOLD INCOME IN THE PAST 12 MONTHS</li>
</ul>
<p>For each group, a list of variables can be found on a corresponding census.gov website. For example, to find the variables in the SEX BY AGE group, you can go to <a href="https://api.census.gov/data/2018/acs/acs5/groups/B01001.html" class="uri">https://api.census.gov/data/2018/acs/acs5/groups/B01001.html</a> (notice the URL ending is the same as the group). There you will find variables such as</p>
<ul>
<li>B01001_001E Estimate!!Total</li>
<li>B01001_002E Estimate!!Total!!Male</li>
<li>B01001_026E Estimate!!Total!!Female</li>
</ul>
<p>And many more. Variables that end in E are estimates. For each one there is often a margin of error, which is the same code ending in M instead of E. Finally for both estimates and margins of error, there may be annotations (e.g. B01001_002EA and B01001_002MA), if these numbers are missing or not straightforward. Details about annotation meanings can be found <a href="https://www.census.gov/data/developers/data-sets/acs-1year/notes-on-acs-estimate-and-annotation-values.html" target="_blank">here</a>. This is just an overview of what the ACS5 variable names look like.</p>
</div>
<div id="geography-units" class="section level3 unnumbered">
<h3>Geography Units</h3>
<p>Census data are available at many levels related to geographical units. The smallest unit is called a census “block” and typically covers between 600 and 3000 people. A collection of blocks forms a census tract (2500 to 8000 people). But US states are also divided into counties, and both state and county identifiers can be used as region selectors. Note that to use the Census API, one has to use numerical identifiers for states and counties. For example, the borough of Brooklyn is actually Kings County, New York, which is county 047 in state 36. And yes, you have to include all three digits, including the leading zero, to identify individual counties. Zipcode tabulation areas (aka ZCTA) is another option, wherein you specify the five-digit zip code. We will want to use that, because NYC provided COVID-19 testing data at the zipcode level.</p>
<div id="borough-level-data" class="section level4 unnumbered">
<h4>Borough-level data</h4>
<p>First, let’s retrieve some data about the five boroughs. Let’s start with the simplest example and get the size of each borough population.</p>
<p>We will need to request the variable B01001_001E, which is the total population estimate.</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="nyc-covid-19-data.html#cb106-1" aria-hidden="true" tabindex="-1"></a>acs_boro_population <span class="ot">&lt;-</span> <span class="fu">getCensus</span>(<span class="at">name =</span> <span class="st">&quot;acs/acs5&quot;</span>,</span>
<span id="cb106-2"><a href="nyc-covid-19-data.html#cb106-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">vintage =</span> <span class="dv">2018</span>,</span>
<span id="cb106-3"><a href="nyc-covid-19-data.html#cb106-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">vars =</span> <span class="fu">c</span>(<span class="st">&quot;NAME&quot;</span>, <span class="st">&quot;B01001_001E&quot;</span>),</span>
<span id="cb106-4"><a href="nyc-covid-19-data.html#cb106-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">region =</span> <span class="st">&quot;county:005,047,061,081,085&quot;</span>,</span>
<span id="cb106-5"><a href="nyc-covid-19-data.html#cb106-5" aria-hidden="true" tabindex="-1"></a>                         <span class="at">regionin =</span> <span class="st">&quot;state:36&quot;</span> , <span class="at">key =</span> myKey</span>
<span id="cb106-6"><a href="nyc-covid-19-data.html#cb106-6" aria-hidden="true" tabindex="-1"></a>                         )</span>
<span id="cb106-7"><a href="nyc-covid-19-data.html#cb106-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb106-8"><a href="nyc-covid-19-data.html#cb106-8" aria-hidden="true" tabindex="-1"></a>acs_boro_population</span></code></pre></div>
<pre><code>##   state county                      NAME B01001_001E
## 1    36    081   Queens County, New York     2298513
## 2    36    061 New York County, New York     1632480
## 3    36    005    Bronx County, New York     1437872
## 4    36    047    Kings County, New York     2600747
## 5    36    085 Richmond County, New York      474101</code></pre>
<p>Cool! We’ve established that we can pull some borough-level information from the US Census to complement data provided by the city or state. Note that the two tables, the one from NYC and the one from the census, don’t exactly match up. For one thing, the county names do not align with the borough names.</p>
</div>
<div id="using-named-vectors-as-look-up-tools" class="section level4 unnumbered">
<h4>Using named vectors as look-up tools</h4>
<p>Now, we can fix this by hand, but there are good ways and less good ways to do this. Ideally, we create a look-up table which we can reuse whenever we need to switch between borough and county names. For those familiar with database “join” operations, it is indeed possible to use joins in R. However, a simple way to just convert between two different representations (e.g., country name and borough name) is to use “named vectors” in R. Here’s how:</p>
<p>Here’s is one way we can use this new lookup table. Note that <code>getBoro</code> is not a function (it is a named vector). So we use square brackets to index it, not parentheses.</p>
<pre><code>## Richmond County, New York 
##           &quot;Staten Island&quot;</code></pre>
<pre><code>##                 Brooklyn 
## &quot;Kings County, New York&quot;</code></pre>
<pre><code>##   state county                      NAME B01001_001E       Borough
## 1    36    081   Queens County, New York     2298513        Queens
## 2    36    061 New York County, New York     1632480     Manhattan
## 3    36    005    Bronx County, New York     1437872     The Bronx
## 4    36    047    Kings County, New York     2600747      Brooklyn
## 5    36    085 Richmond County, New York      474101 Staten Island</code></pre>
<p>All that remains is that annoying variable name B01001_001E for Total Population. We should definitely fix this, and there are a few ways to do it. The following may seem like a long-winded way to go about it, but it has the benefit that it will work no matter where the variable B01001_001E appears. It won’t accidentally change the wrong column name, and it won’t do anything at all if the variable you are trying to rename doesn’t exist.</p>
<pre><code>##   state county                countyName Total_Pop       Borough
## 1    36    081   Queens County, New York   2298513        Queens
## 2    36    061 New York County, New York   1632480     Manhattan
## 3    36    005    Bronx County, New York   1437872     The Bronx
## 4    36    047    Kings County, New York   2600747      Brooklyn
## 5    36    085 Richmond County, New York    474101 Staten Island</code></pre>
<p>(If you’re wondering whether we could have used named vectors to convert between the ACS names, like B01001_001E, and simple names like “Total_Pop,” then yes, but you’re getting ahead of me. Once we have more than a few of these variables, that would indeed be a good idea.)</p>
<p>With this in hand, we can now combine our NYC COVID-19 data with our Census data. Let’s bring back our first borough table:</p>
<pre><code>##   BOROUGH_GROUP COVID_CASE_COUNT COVID_CASE_RATE
## 1     The Bronx            28875         1962.05
## 2      Brooklyn            34476         1269.58
## 3     Manhattan            16754          887.36
## 4        Queens            39856         1589.55
## 5 Staten Island             9755         1944.40
## 6      Citywide           129788              NA</code></pre>
<p>We will make some judicious use of dplyr here to simplify the outcome. Mostly, we want to get rid of unnecessary columns from the ACS table (using <code>select</code>), and then use <code>join()</code> to merge the two tables. The advantage of the pipe operatore <code>%&gt;%</code> is that it allows us to think of our data as going through a flow of operations. First we take our table of data, then we select the columns we care about, then we combine it with our other table (the NYC data on COVID-19):</p>
<pre><code>##         Borough                countyName Total_Pop COVID_CASE_COUNT
## 1        Queens   Queens County, New York   2298513            39856
## 2     Manhattan New York County, New York   1632480            16754
## 3     The Bronx    Bronx County, New York   1437872            28875
## 4      Brooklyn    Kings County, New York   2600747            34476
## 5 Staten Island Richmond County, New York    474101             9755
##   COVID_CASE_RATE
## 1         1589.55
## 2          887.36
## 3         1962.05
## 4         1269.58
## 5         1944.40</code></pre>
<p>Woohoo! (I’m keeping countyName for later. You’ll see why.)</p>
<p><strong>Worked Example</strong>: Compute the population adjusted rate per 100,000 people using population data from the census. How does it differ from the age-adjusted rate?</p>
<p>We can use our population estimates (keep in mind that these are 5-year averages as of 2018) to derive our own rate-per-100,000 as follows</p>
<pre><code>##         Borough COVID_CASE_RATE RATE_100K
## 1        Queens         1589.55   1733.99
## 2     Manhattan          887.36   1026.29
## 3     The Bronx         1962.05   2008.18
## 4      Brooklyn         1269.58   1325.62
## 5 Staten Island         1944.40   2057.58</code></pre>
<p>You’ll notice that our rate, which is not age-adjusted, differs somewhat from the NYC rate, which is age-adjusted. Aside from age-adjustment, it is possible that our population numbers (based on 5-year averages) are different from the latest NYC populations estimates. If our population numbers are lower, then our rates would be higher. Or the difference could be a result of the age-adjustment formula.</p>
<!-- ```{r} -->
<!-- boro_join %>% select(Borough, COVID_CASE_RATE, RATE_100K) %>% -->
<!--   mutate(normCR1 = round(COVID_CASE_RATE/COVID_CASE_RATE[3],2),  -->
<!--          normCR2 = round(RATE_100K/RATE_100K[3],2)) -->
<!-- ``` -->
</div>
<div id="more-variables-income-age-and-race" class="section level4 unnumbered">
<h4>More variables: income, age, and race</h4>
<p>To request the median household income we will request the variable “B19013_001E” (intuitive, right?) Alternatively, the variable B20017_001E is earnings per person not by household. Why not examine both?</p>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="nyc-covid-19-data.html#cb115-1" aria-hidden="true" tabindex="-1"></a>acs_boro_income <span class="ot">&lt;-</span> <span class="fu">getCensus</span>(<span class="at">name =</span> <span class="st">&quot;acs/acs5&quot;</span>,</span>
<span id="cb115-2"><a href="nyc-covid-19-data.html#cb115-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">vintage =</span> <span class="dv">2018</span>,</span>
<span id="cb115-3"><a href="nyc-covid-19-data.html#cb115-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">vars =</span> <span class="fu">c</span>(<span class="st">&quot;NAME&quot;</span>, <span class="st">&quot;B19013_001E&quot;</span>, <span class="st">&quot;B20017_001E&quot;</span>),</span>
<span id="cb115-4"><a href="nyc-covid-19-data.html#cb115-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">region =</span> <span class="st">&quot;county:005,047,061,081,085&quot;</span>,</span>
<span id="cb115-5"><a href="nyc-covid-19-data.html#cb115-5" aria-hidden="true" tabindex="-1"></a>                         <span class="at">regionin =</span> <span class="st">&quot;state:36&quot;</span> , <span class="at">key =</span> myKey</span>
<span id="cb115-6"><a href="nyc-covid-19-data.html#cb115-6" aria-hidden="true" tabindex="-1"></a>                         )</span>
<span id="cb115-7"><a href="nyc-covid-19-data.html#cb115-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb115-8"><a href="nyc-covid-19-data.html#cb115-8" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(acs_boro_income)[<span class="fu">which</span>(<span class="fu">names</span>(acs_boro_income)<span class="sc">==</span><span class="st">&quot;B19013_001E&quot;</span>)] <span class="ot">&lt;-</span> <span class="st">&quot;Median_HH_Income&quot;</span></span>
<span id="cb115-9"><a href="nyc-covid-19-data.html#cb115-9" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(acs_boro_income)[<span class="fu">which</span>(<span class="fu">names</span>(acs_boro_income)<span class="sc">==</span><span class="st">&quot;B20017_001E&quot;</span>)] <span class="ot">&lt;-</span> <span class="st">&quot;Median_Income&quot;</span></span>
<span id="cb115-10"><a href="nyc-covid-19-data.html#cb115-10" aria-hidden="true" tabindex="-1"></a>acs_boro_income</span></code></pre></div>
<pre><code>##   state county                      NAME Median_HH_Income Median_Income
## 1    36    081   Queens County, New York            64987         36381
## 2    36    061 New York County, New York            82459         59620
## 3    36    005    Bronx County, New York            38085         27074
## 4    36    047    Kings County, New York            56015         37123
## 5    36    085 Richmond County, New York            79267         46586</code></pre>
<p>There it is, five-year averages, inflation-adjusted for 2018 dollars, by borough. (If you see one-year estimates, they may be a bit higher than these numbers, if wages went up faster than inflation).</p>
<p>We can add these new income variables to the table we’ve started to build</p>
<pre><code>##         Borough                countyName Total_Pop COVID_CASE_COUNT
## 1        Queens   Queens County, New York   2298513            39856
## 2     Manhattan New York County, New York   1632480            16754
## 3     The Bronx    Bronx County, New York   1437872            28875
## 4      Brooklyn    Kings County, New York   2600747            34476
## 5 Staten Island Richmond County, New York    474101             9755
##   COVID_CASE_RATE RATE_100K Median_HH_Income Median_Income
## 1         1589.55   1733.99            64987         36381
## 2          887.36   1026.29            82459         59620
## 3         1962.05   2008.18            38085         27074
## 4         1269.58   1325.62            56015         37123
## 5         1944.40   2057.58            79267         46586</code></pre>
<p>In the next part of the series, we will keep assembling more variables related to age and race. We will also eventually change our unit of analysis to zipcode tabulation areas.</p>
</div>
</div>
</div>
<div id="part3" class="section level2" number="15.3">
<h2><span class="header-section-number">15.3</span> More (and messier) Census data</h2>
<div id="exploring-the-acs-data" class="section level3 unnumbered">
<h3>Exploring the ACS data</h3>
<p>So far, we have been selecting one or two variables at a time, because we knew what we were looking for. Sometimes, though, you’re not exactly sure what variables are in the data. Moreoever, since many of the ACS tables combine categories (such as SEX BY AGE), the number of variables grows exponentially (e.g., as the number of SEX categories times the number of AGE categories). Add to that the margin-of-error and annotation variables, and the list gets overwhelming fast.</p>
<p>Even data from the SEX BY AGE group (B01001), which seems simple, is rather complicated-looking! I will walk through it deliberately, as I would do if I were exploring the data for the first time and not sure what I was going to find.</p>
<p>First, I will use the function <code>listCensusMetadata</code> to request all of the variables in the group B01001 and see what we see.</p>
<pre><code>##             name                                                     label
## 139  B01001_001E                                           Estimate!!Total
## 41  B01001_001EA                             Annotation of Estimate!!Total
## 140  B01001_001M                                    Margin of Error!!Total
## 42  B01001_001MA                      Annotation of Margin of Error!!Total
## 137  B01001_002E                                     Estimate!!Total!!Male
## 53  B01001_002EA                       Annotation of Estimate!!Total!!Male
## 138  B01001_002M                              Margin of Error!!Total!!Male
## 54  B01001_002MA                Annotation of Margin of Error!!Total!!Male
## 143  B01001_003E                      Estimate!!Total!!Male!!Under 5 years
## 50  B01001_003EA        Annotation of Estimate!!Total!!Male!!Under 5 years
## 144  B01001_003M               Margin of Error!!Total!!Male!!Under 5 years
## 51  B01001_003MA Annotation of Margin of Error!!Total!!Male!!Under 5 years
## 141  B01001_004E                       Estimate!!Total!!Male!!5 to 9 years
## 52  B01001_004EA         Annotation of Estimate!!Total!!Male!!5 to 9 years
## 142  B01001_004M                Margin of Error!!Total!!Male!!5 to 9 years
##        concept predicateType  group limit predicateOnly
## 139 SEX BY AGE           int B01001     0          TRUE
## 41  SEX BY AGE        string B01001     0          TRUE
## 140 SEX BY AGE           int B01001     0          TRUE
## 42  SEX BY AGE        string B01001     0          TRUE
## 137 SEX BY AGE           int B01001     0          TRUE
## 53  SEX BY AGE        string B01001     0          TRUE
## 138 SEX BY AGE           int B01001     0          TRUE
## 54  SEX BY AGE        string B01001     0          TRUE
## 143 SEX BY AGE           int B01001     0          TRUE
## 50  SEX BY AGE        string B01001     0          TRUE
## 144 SEX BY AGE           int B01001     0          TRUE
## 51  SEX BY AGE        string B01001     0          TRUE
## 141 SEX BY AGE           int B01001     0          TRUE
## 52  SEX BY AGE        string B01001     0          TRUE
## 142 SEX BY AGE           int B01001     0          TRUE</code></pre>
<p>Ugh. Note that our table of variables here includes variable name, label, and type. For type, we have “int” for integers (numbers) and “string” which is the computational shorthand for “string of characters.” This is the variable-type used for words and sentences as well as passwords or other random strings of characters.</p>
<p>To make the results more readable, we can try identify the pattern in the order of the variables. First, let’s observe the following. The numbers after the group name are just increasing from 001, 002, and so on. We might want to look at the middle of this list, e.g, from 020 to 030, which we can do as follows:</p>
<pre><code>##           name                                    label    concept
## 1  B01001_020E   Estimate!!Total!!Male!!65 and 66 years SEX BY AGE
## 2  B01001_021E    Estimate!!Total!!Male!!67 to 69 years SEX BY AGE
## 3  B01001_022E    Estimate!!Total!!Male!!70 to 74 years SEX BY AGE
## 4  B01001_023E    Estimate!!Total!!Male!!75 to 79 years SEX BY AGE
## 5  B01001_024E    Estimate!!Total!!Male!!80 to 84 years SEX BY AGE
## 6  B01001_025E Estimate!!Total!!Male!!85 years and over SEX BY AGE
## 7  B01001_026E                  Estimate!!Total!!Female SEX BY AGE
## 8  B01001_027E   Estimate!!Total!!Female!!Under 5 years SEX BY AGE
## 9  B01001_028E    Estimate!!Total!!Female!!5 to 9 years SEX BY AGE
## 10 B01001_029E  Estimate!!Total!!Female!!10 to 14 years SEX BY AGE
## 11 B01001_030E  Estimate!!Total!!Female!!15 to 17 years SEX BY AGE
##    predicateType  group limit predicateOnly
## 1            int B01001     0          TRUE
## 2            int B01001     0          TRUE
## 3            int B01001     0          TRUE
## 4            int B01001     0          TRUE
## 5            int B01001     0          TRUE
## 6            int B01001     0          TRUE
## 7            int B01001     0          TRUE
## 8            int B01001     0          TRUE
## 9            int B01001     0          TRUE
## 10           int B01001     0          TRUE
## 11           int B01001     0          TRUE</code></pre>
<p>We’ve learned the following. The variable names (after the total) begin with males. First all males, then males by increasing age group. The females. Although it looks like it from this sample, the age groups are not all in intervals of 5 years. There are groups of three, two, and even one (e.g., 15-17, 18-19, 20 years). I’m not sure why.</p>
<p>Suppose we wanted to extract the percentage of the population over the age of 65. From this table we would need to do the following</p>
<ul>
<li>add up the counts of males in each of the intervals over 65
<ul>
<li>B01001_020E + B01001_021E + … + B01001_025E</li>
</ul></li>
<li>add to this the counts of females in the same age intervals
<ul>
<li>B01001_044E + B01001_045E + … + B01001_049E</li>
</ul></li>
<li>divide by the total
<ul>
<li>B01001_001E</li>
</ul></li>
</ul>
<pre><code>##         Borough over65
## 1        Queens   14.8
## 2     Manhattan   15.8
## 3     The Bronx   12.1
## 4      Brooklyn   13.2
## 5 Staten Island   15.5</code></pre>
<p>I don’t know if you were expecting those results, but Manhattan has the highest proportion of adults over 65, while the Bronx has the lowest. We know that older adults have a higher rate of infection with COVID-19, and yet infection rates in the Bronx are much higher than in Manhattan. Possibly there is more to the story than age-by-borough.</p>
<p>If all of the above seems not worth the effort to get proportion over 65, you might want to just extact something like median age per geographic unit. These are variables in the SEX BY AGE group.</p>
<ul>
<li>B01002_001E Estimate!!Median age –!!Total</li>
<li>B01002_002E Estimate!!Median age –!!Male</li>
<li>B01002_003E Estimate!!Median age –!!Female</li>
</ul>
<pre><code>##   state county                      NAME Median_Age Median_Age_Male
## 1    36    081   Queens County, New York       38.7            37.2
## 2    36    061 New York County, New York       37.3            36.7
## 3    36    005    Bronx County, New York       33.9            31.7
## 4    36    047    Kings County, New York       35.1            33.5
## 5    36    085 Richmond County, New York       40.0            38.3
##   Median_Age_Female
## 1              40.0
## 2              37.9
## 3              35.9
## 4              36.4
## 5              41.3</code></pre>
<p>Interestingly, the medianAge puts Staten Island and Queens as older than Manhattan. So median age and proportion over 65 do not rank the Boroughs the same after all.</p>
<p>To match the NYC race-level data we will need these categories of Race/Ethnicity</p>
<ul>
<li>All Hispanic</li>
<li>Non-Hispanic/Latino: Black,African American</li>
<li>Non-Hispanic/Latino: White</li>
<li>Non-Hispanic/Latino: Asian</li>
<li>Non-Hispanic/Latino: Other</li>
</ul>
<p>First we need to find the necessary race variables. The Census organizes race information in different variable groups, some of which separate out Hispanic or Latino origin (B03002) and some which do not (B02001). We will use the first one, again to match the way NYC has been reporting health data.</p>
<pre><code>##            name
## 29  B03002_001E
## 67 B03002_001EA
## 30  B03002_001M
## 68 B03002_001MA
## 37  B03002_002E
## 70 B03002_002EA
## 38  B03002_002M
## 69 B03002_002MA
## 35  B03002_003E
## 78 B03002_003EA
## 36  B03002_003M
## 77 B03002_003MA
## 33  B03002_004E
## 80 B03002_004EA
## 34  B03002_004M
## 79 B03002_004MA
## 31  B03002_005E
## 82 B03002_005EA
## 32  B03002_005M
## 81 B03002_005MA
##                                                                                                    label
## 29                                                                                       Estimate!!Total
## 67                                                                         Annotation of Estimate!!Total
## 30                                                                                Margin of Error!!Total
## 68                                                                  Annotation of Margin of Error!!Total
## 37                                                               Estimate!!Total!!Not Hispanic or Latino
## 70                                                 Annotation of Estimate!!Total!!Not Hispanic or Latino
## 38                                                        Margin of Error!!Total!!Not Hispanic or Latino
## 69                                          Annotation of Margin of Error!!Total!!Not Hispanic or Latino
## 35                                                  Estimate!!Total!!Not Hispanic or Latino!!White alone
## 78                                    Annotation of Estimate!!Total!!Not Hispanic or Latino!!White alone
## 36                                           Margin of Error!!Total!!Not Hispanic or Latino!!White alone
## 77                             Annotation of Margin of Error!!Total!!Not Hispanic or Latino!!White alone
## 33                              Estimate!!Total!!Not Hispanic or Latino!!Black or African American alone
## 80                Annotation of Estimate!!Total!!Not Hispanic or Latino!!Black or African American alone
## 34                       Margin of Error!!Total!!Not Hispanic or Latino!!Black or African American alone
## 79         Annotation of Margin of Error!!Total!!Not Hispanic or Latino!!Black or African American alone
## 31                      Estimate!!Total!!Not Hispanic or Latino!!American Indian and Alaska Native alone
## 82        Annotation of Estimate!!Total!!Not Hispanic or Latino!!American Indian and Alaska Native alone
## 32               Margin of Error!!Total!!Not Hispanic or Latino!!American Indian and Alaska Native alone
## 81 Annotation of Margin of Error!!Total!!Not Hispanic or Latino!!American Indian and Alaska Native alone
##                              concept predicateType  group limit predicateOnly
## 29 HISPANIC OR LATINO ORIGIN BY RACE           int B03002     0          TRUE
## 67 HISPANIC OR LATINO ORIGIN BY RACE        string B03002     0          TRUE
## 30 HISPANIC OR LATINO ORIGIN BY RACE           int B03002     0          TRUE
## 68 HISPANIC OR LATINO ORIGIN BY RACE        string B03002     0          TRUE
## 37 HISPANIC OR LATINO ORIGIN BY RACE           int B03002     0          TRUE
## 70 HISPANIC OR LATINO ORIGIN BY RACE        string B03002     0          TRUE
## 38 HISPANIC OR LATINO ORIGIN BY RACE           int B03002     0          TRUE
## 69 HISPANIC OR LATINO ORIGIN BY RACE        string B03002     0          TRUE
## 35 HISPANIC OR LATINO ORIGIN BY RACE           int B03002     0          TRUE
## 78 HISPANIC OR LATINO ORIGIN BY RACE        string B03002     0          TRUE
## 36 HISPANIC OR LATINO ORIGIN BY RACE           int B03002     0          TRUE
## 77 HISPANIC OR LATINO ORIGIN BY RACE        string B03002     0          TRUE
## 33 HISPANIC OR LATINO ORIGIN BY RACE           int B03002     0          TRUE
## 80 HISPANIC OR LATINO ORIGIN BY RACE        string B03002     0          TRUE
## 34 HISPANIC OR LATINO ORIGIN BY RACE           int B03002     0          TRUE
## 79 HISPANIC OR LATINO ORIGIN BY RACE        string B03002     0          TRUE
## 31 HISPANIC OR LATINO ORIGIN BY RACE           int B03002     0          TRUE
## 82 HISPANIC OR LATINO ORIGIN BY RACE        string B03002     0          TRUE
## 32 HISPANIC OR LATINO ORIGIN BY RACE           int B03002     0          TRUE
## 81 HISPANIC OR LATINO ORIGIN BY RACE        string B03002     0          TRUE</code></pre>
<p>Okay we’re on the right track but it would be nice to see this list without the margin of errors and annotation variables. How can we get a list of variables that end in E but not in M or EA or MA? The answer is something called regular expressions, which is a specialist term for pattern matching. This is a long topic, so we are just going to work out one type of example, which is matching strings with a specific ending. The R function for “get regular expression” is called <code>grep()</code>.</p>
<pre><code>## [1] 1 2</code></pre>
<p>By default <code>grep</code> returns the indices of the matched values, not the values themselves. In this case, the first two words matched. If we want the values, we use <code>grep</code> with the <code>value=TRUE</code> option as follows</p>
<pre><code>## [1] &quot;apple&quot;  &quot;orange&quot;</code></pre>
<p>You can probably guess how to modify this pattern to find the string ending in “a” instead. If you want both, that is strings ending in either “a” or “e,” this is the way to do it. By the way, the pattern matching is case-sensitive.</p>
<pre><code>## [1] &quot;apple&quot;  &quot;orange&quot; &quot;banana&quot;</code></pre>
<p>With this, let’s reduce the list of variables</p>
<pre><code>##           name
## 25 B03002_021E
## 27 B03002_020E
## 29 B03002_001E
## 31 B03002_005E
## 33 B03002_004E
## 35 B03002_003E
##                                                                                                                   label
## 25 Estimate!!Total!!Hispanic or Latino!!Two or more races!!Two races excluding Some other race, and three or more races
## 27                          Estimate!!Total!!Hispanic or Latino!!Two or more races!!Two races including Some other race
## 29                                                                                                      Estimate!!Total
## 31                                     Estimate!!Total!!Not Hispanic or Latino!!American Indian and Alaska Native alone
## 33                                             Estimate!!Total!!Not Hispanic or Latino!!Black or African American alone
## 35                                                                 Estimate!!Total!!Not Hispanic or Latino!!White alone
##                              concept predicateType  group limit predicateOnly
## 25 HISPANIC OR LATINO ORIGIN BY RACE           int B03002     0          TRUE
## 27 HISPANIC OR LATINO ORIGIN BY RACE           int B03002     0          TRUE
## 29 HISPANIC OR LATINO ORIGIN BY RACE           int B03002     0          TRUE
## 31 HISPANIC OR LATINO ORIGIN BY RACE           int B03002     0          TRUE
## 33 HISPANIC OR LATINO ORIGIN BY RACE           int B03002     0          TRUE
## 35 HISPANIC OR LATINO ORIGIN BY RACE           int B03002     0          TRUE</code></pre>
<p>With this easier to parse table, we can select the variables we want in particular:</p>
<ul>
<li>B03002_001E Estimate!!Total<br />
</li>
<li>B03002_002E Estimate!!Total!!Not Hispanic or Latino</li>
<li>B03002_003E Estimate!!Total!!Not Hispanic or Latino!!White alone</li>
<li>B03002_004E Estimate!!Total!!Not Hispanic or Latino!!Black or African American alone</li>
<li>B03002_006E Estimate!!Total!!Not Hispanic or Latino!!Asian alone</li>
<li>B03002_012E Estimate!!Total!!Hispanic or Latino</li>
</ul>
<p>We’ll use the first two for normalizing proportions and for determining the non-Hispanic “Other” category. To get race by borough,</p>
<pre><code>##   Hisp_Latin NH_Black NH_White NH_Asian NH_Other       Borough
## 1       28.0     17.2     25.3     25.1      4.4        Queens
## 2       26.0     12.5     46.9     11.9      2.8     Manhattan
## 3       55.9     29.3      9.3      3.5      2.0     The Bronx
## 4       19.2     30.3     36.2     11.7      2.6      Brooklyn
## 5       18.3      9.3     61.7      8.6      2.1 Staten Island</code></pre>
</div>
</div>
<div id="zipcode" class="section level2" number="15.4">
<h2><span class="header-section-number">15.4</span> Zipcode tabulation area</h2>
<p>As we mentioned above, it is possible to query the Census for zipcode tabulation areas. You need to specify which zipcodes, you want. We will get our list from the NYC data, because those are the zipcodes for which we have COVID-19 case counts.</p>
<p>In the code below, I will extract the zip codes and make one long string (“10001, 10002, 10003, 10004, … , 11694, 11697”) to pass to the Census API query.</p>
<pre><code>## [1] &quot;10001,10002,10003,10004,10005,10006,10007,&quot;</code></pre>
<p>Having done that, we do our queries as before for borough data, only instead of county and state region, we use “zip code tabulation area:” followed by our long string of zip codes.</p>
<div id="zipcode-level-median-income" class="section level4 unnumbered">
<h4>Zipcode-level median income</h4>
<p>Remember how we were renaming all of the Census variables by hand before? That was a pain. Having seen many of the variables that we were interested in, an alternative is to keep a table running of these variables alongside our preferred name.</p>
<p>For example, here is one way to do it. From the 20,000 available census variables, these are the 20-30 variables I may want. (I also included region variables for county and zip code). You can always add to this table.</p>
<pre><code>##                    acsName         realName
## 1                     NAME       countyName
## 2 zip_code_tabulation_area          zipcode
## 3              B01001_001E        Total_Pop
## 4              B01002_001E       Median_Age
## 5              B01002_002E  Median_Age_Male
## 6              B01002_003E   Median_Age_Fem
## 7              B01003_001E       Population
## 8              B19013_001E Median_HH_Income
## 9              B20017_001E    Median_Income</code></pre>
<p>I can then use the named-vector trick from before to convert between the acsName and the realName I like.</p>
<pre><code>##   zipcode Median_HH_Income Median_Income
## 1   10472            30977         22953
## 2   10309           103175         54948
## 3   10467            37015         26938
## 4   10456            27106         22862
## 5   10001            88526         74878
## 6   10035            30081         32731</code></pre>
<p>That was easy!</p>
</div>
<div id="zipcode-level-race-age-etc." class="section level4 unnumbered">
<h4>Zipcode-level race, age, etc.</h4>
<p>We can now redo the rest of our queries at the zip code level, including any age, sex, and race variables that we want to include.</p>
<pre><code>##   zipcode zcta_propOver65
## 1   10472            11.1
## 2   10309            15.5
## 3   10467            11.0
## 4   10456             9.0
## 5   10001            14.8
## 6   10035            12.6</code></pre>
<pre><code>##   zipcode Total_Pop Median_Age Median_Age_Male Median_Age_Fem
## 1   10472     68796       32.1            30.0           33.9
## 2   10309     33531       40.5            37.6           43.1
## 3   10467    103732       33.7            32.5           34.7
## 4   10456     94218       30.9            28.7           32.7
## 5   10001     22924       36.7            40.1           34.3
## 6   10035     35743       36.3            35.1           37.4</code></pre>
<pre><code>##   zipcode Total_HispRace Hisp_Latin NH_Black NH_White NH_Asian NH_Other
## 1   10472          68796       64.5     23.8      2.6      6.5      2.6
## 2   10309          33531        9.3      0.6     85.0      3.6      1.5
## 3   10467         103732       52.3     30.4      9.4      5.7      2.1
## 4   10456          94218       61.5     34.3      1.2      0.8      2.1
## 5   10001          22924       14.2      5.6     53.1     25.0      2.1
## 6   10035          35743       44.6     37.0     10.2      4.4      3.8</code></pre>
</div>
<div id="some-more-variables-to-play-with" class="section level3 unnumbered">
<h3>Some more variables to play with</h3>
<p>While we’re at it, we can keep collecting variables related to the reports we read. For example, household size seems to be associated with prevalence of COVID-19 and so does the share of college-educated adults (recall the image at the beginning of this chapter—by the way, we’re almost ready to make our own, even better, version of it). The ACS5 variables we will need are:</p>
<div id="household-size" class="section level4 unnumbered">
<h4>Household size</h4>
<ul>
<li>B08201_007E Estimate!!Total!!1-person household</li>
<li>B08201_013E Estimate!!Total!!2-person household</li>
<li>B08201_019E Estimate!!Total!!3-person household</li>
<li>B08201_025E Estimate!!Total!!4-or-more-person household</li>
</ul>
</div>
<div id="educational-attainment" class="section level4 unnumbered">
<h4>Educational attainment</h4>
<ul>
<li>B15003_022E Estimate!!Total!!Bachelor’s degree<br />
</li>
<li>B15003_023E Estimate!!Total!!Master’s degree<br />
</li>
<li>B15003_024E Estimate!!Total!!Professional school degree</li>
<li>B15003_025E Estimate!!Total!!Doctorate degree</li>
</ul>
<p>I’ve already added those to the <code>acsVars</code> table, so we can use the <code>getRealName</code> vector to convert the names to human-readable versions.</p>
<pre><code>##   zipcode Bachelors Masters Professional Doctorate Total_EducPop HH1pers
## 1   10472      3856    1111          214        27         42234    5550
## 2   10309      5129    2207          448       121         23537    1934
## 3   10467      8921    2999          715       315         67420   11847
## 4   10456      5566    1333          198       101         56252    8552
## 5   10001      6810    3676         1190       557         17985    6710
## 6   10035      4343    2118          540       198         25962    6621
##   HH2pers HH3pers HH4plus Bach_plus_prop    AvgHH
## 1    5200    4002    7135           12.3 2.581258
## 2    3323    2239    3968           33.6 2.718859
## 3    8992    6351    9542           19.2 2.369923
## 4    7338    5505    9379           12.8 2.510528
## 5    3897    1072     752           68.0 1.667444
## 6    3627    2219    1961           27.7 1.966731</code></pre>
<p>Having gathered the information in various tables (zcta_income, zcta_propOver65, zcta_SexByAge
zcta_race_proportion, zcta_edu_hh), we can finally combine them all into one giant zipcode data frame:</p>
<pre><code>##  [1] &quot;zipcode&quot;           &quot;Median_HH_Income&quot;  &quot;Median_Income&quot;    
##  [4] &quot;zcta_propOver65&quot;   &quot;Total_Pop&quot;         &quot;Median_Age&quot;       
##  [7] &quot;Median_Age_Male&quot;   &quot;Median_Age_Fem&quot;    &quot;Total_HispRace&quot;   
## [10] &quot;Hisp_Latin&quot;        &quot;NH_Black&quot;          &quot;NH_White&quot;         
## [13] &quot;NH_Asian&quot;          &quot;NH_Other&quot;          &quot;Bachelors&quot;        
## [16] &quot;Masters&quot;           &quot;Professional&quot;      &quot;Doctorate&quot;        
## [19] &quot;Total_EducPop&quot;     &quot;HH1pers&quot;           &quot;HH2pers&quot;          
## [22] &quot;HH3pers&quot;           &quot;HH4plus&quot;           &quot;Bach_plus_prop&quot;   
## [25] &quot;AvgHH&quot;             &quot;Positive&quot;          &quot;Total&quot;            
## [28] &quot;zcta_cum.perc_pos&quot;</code></pre>
<p>And there you have it. 27 variables, each associated with a NYC zip code. Now what do you do once you have all of that? Probably make some pictures. Finally!</p>
</div>
</div>
</div>
<div id="mapviz" class="section level2" number="15.5">
<h2><span class="header-section-number">15.5</span> Visualizing data on maps</h2>
<p>The whole point of using zip codes as units was that they represent distinct geographic areas. It is not easy to make sense of a list of 177 household income values, ordered by zip code. But if we convert these values to colors or shades and use those to fill in the zip code boundaries of a map, then we can “see” where the money is and where it isn’t.</p>
<div id="shapefiles" class="section level3 unnumbered">
<h3>Shapefiles</h3>
<p>To carry out this feat, we will need to enlist the help of a <strong>shapefile</strong>, which is a data format that was specifically invented for geographical information systems (GIS). You don’t need to understand the detailed structure of a shapefile. You only need to know that it will allow you to map, say, the zip code 10003 to some region on a drawing.</p>
<p>So we will need a shapefile for NYC zip codes. Search for this on the internet, and you’ll get one <a href="https://catalog.data.gov/dataset/zip-code-boundaries" target="_blank">here</a>. We will need the R package that will do the translation work for us. It is called “R geospatial data abstraction library (<code>rgdal</code>).” Lastly, to produce images like you see in the media, we might need some color palettes. These will map numbers (e.g., proportion over 65) to colors in ways that are designed to be visually distinctive.</p>
<pre><code>## OGR data source with driver: ESRI Shapefile 
## Source: &quot;/Users/bergner/GitHub/carpe-datum/Shape_Files/ZIP_CODE_040114.shp&quot;, layer: &quot;ZIP_CODE_040114&quot;
## with 263 features
## It has 12 fields</code></pre>
<p>The data structure of the shapefile is pretty complicated. (Look inside, I dare you!)
But right off the bat, we can plot it</p>
<p><img src="carpedatum_files/figure-html/unnamed-chunk-81-1.png" width="90%" style="display: block; margin: auto;" /></p>
<p>Woot! There be zipcodes! Without any other data. Just… boundaries. If you are following along in an RStudio session, you can get a better quality image by uncommenting the <code>quartz()</code> command. This will open the drawing in a new window. Note that it takes a little while to finish, and you can see it draw the boundaries of each zipcode one at a time… aww!</p>
<p>To add colors or shades, we will need to send color/shade information along with the plot instruction… but there’s something else we need to do first.</p>
<p>How many zip codes are in our data set? The answer can be found by the number of rows in our data frame:</p>
<pre><code>## [1] 177</code></pre>
<p>Is this the same as the number of zip codes in our shapefile? If it isn’t, then we will get issues when we combine the data we want to map with the geographic boundary data.</p>
<pre><code>## [1] 263</code></pre>
<p>Not only are there more zipcodes in the shapefile than we have data for, but, for whatever reason involving the design of shapefiles, some zipcodes appear more than once. This is a small nuisance, but it can be solved by using <code>join</code> as before. The main idea is that we pass the data we have, and provide “missing” values (<code>NA</code> in R) for everything else.
Here is how to repackage our dataset to fit with the shapefile</p>
<p>Simple enough. We expected there to be zipcodes with missing census/COVID-19 data. Indeed, here are some:</p>
<pre><code>##     zipcode Median_HH_Income Median_Income zcta_propOver65 Total_Pop Median_Age
## 258   11414            71648         45640            22.0     29219       45.0
## 259   10310            72093         44590            13.4     23262       38.8
## 260   11693            59431         44674            12.3     12919       39.5
## 261   11249               NA            NA              NA        NA         NA
## 262   10162               NA            NA              NA        NA         NA
## 263   10119               NA            NA              NA        NA         NA
##     Median_Age_Male Median_Age_Fem Total_HispRace Hisp_Latin NH_Black NH_White
## 258            43.9           46.0          29219       22.3      1.8     67.8
## 259            38.2           39.1          23262       31.6     18.9     41.6
## 260            35.2           43.1          12919       29.5     16.1     46.9
## 261              NA             NA             NA         NA       NA       NA
## 262              NA             NA             NA         NA       NA       NA
## 263              NA             NA             NA         NA       NA       NA
##     NH_Asian NH_Other Bachelors Masters Professional Doctorate Total_EducPop
## 258      5.0      3.0      3828    1737          419        50         21607
## 259      6.2      1.7      2995    1768          409       150         15599
## 260      4.0      3.5      1401     828          114        10          8924
## 261       NA       NA        NA      NA           NA        NA            NA
## 262       NA       NA        NA      NA           NA        NA            NA
## 263       NA       NA        NA      NA           NA        NA            NA
##     HH1pers HH2pers HH3pers HH4plus Bach_plus_prop    AvgHH Positive Total
## 258    2603    3398    2151    2528           27.9 2.431086      588  1004
## 259    1971    2326    1628    2421           34.1 2.539061      506  1136
## 260    1469    1630     779     967           26.4 2.256760      256   444
## 261      NA      NA      NA      NA             NA       NA       NA    NA
## 262      NA      NA      NA      NA             NA       NA       NA    NA
## 263      NA      NA      NA      NA             NA       NA       NA    NA
##     zcta_cum.perc_pos
## 258             58.57
## 259             44.54
## 260             57.66
## 261                NA
## 262                NA
## 263                NA</code></pre>
<p>Why are these zipcodes (and others) missing data? It’s hard to know, and you need to look at it case by case. Some of these are zipcodes for special areas, like industrial zones, airports. and train stations. (10119 appears to be Penn Station).</p>
</div>
<div id="coloring-in-the-shapes" class="section level3 unnumbered">
<h3>Coloring in the shapes</h3>
<p>So, suppose we want to color in the zip code boundaries to indicate the share of college educated adults in each region. We either have the college rate in our data frame, or we have the data needed to calculate it. (In this case, we might have total college and total population, so we can compute the case rate.)</p>
<p>But what is the right way to map case rate, which is a numeric/quantitative variable to color? What kind of variable is color? This is a profound question that has to do with perception through our sense. Questions regarding mental perception of sounds, colors, or short-duration verbal cues, for example, are the domain of <strong>psychophysics</strong> (yes, that’s a real thing!)</p>
<p>Without delving too deeply into this problem, we can at least try to emulate the common practices in similar visualizations. What you’ll see is that in many cases, rather than mapping a continuous range of values (e.g., COVID-19 case rate) to a continuous range of colors/shades, the values and the colors are discretized into a small number of levels. Each zip code area, then, is mapped to one of these levels and thus one of the corresponding colors/shades. In the media reports referenced early in this chapter, five levels was pretty typical.</p>
<div id="an-important-digression-on-choosing-your-levels" class="section level4 unnumbered">
<h4>An important digression on choosing your levels</h4>
<p>Let’s say we want five levels. Sometimes the level-groupings of data are associated with quintiles. Recall that quintiles divide our ordered data set into five equally-sized partitions. Meaning, we will have the same number of zip codes in the lowest quintile, and the next lowest, and so on. But one could also make five partitions where the <em>range of values is equally sized</em> but the number of cases in each partition is not. Think of the bin-breaks in a histogram. These are equally-sized ranges, but each bin does not necessarily have the same number of cases. Say, if the distribution is bell-shaped.</p>
<p>Here is an example using fake data, drawn in fact from a normal distribution:</p>
<pre><code>## quintileAssignments
##  1  2  3  4  5 
## 40 40 40 40 40</code></pre>
<pre><code>## equalRangeAssignments
## (-2.5,-1.5] (-1.5,-0.5]  (-0.5,0.5]   (0.5,1.5]   (1.5,2.5] 
##           1          28         142          29           0</code></pre>
<p>As you can see, the number of cases that get collected in these buckets can be different, depending on how we slice it. If we were mapping zipcodes to colors based on the values of some data such as these, then we would get very different maps. In the quantile case (quintiles, specifically!), we would have our colors spread out, or varying, more. In the equal range case, we may have only a few extreme colors, while the majority of the zipcodes are the same color. All of this happened because our data distribution was bell-shaped. Admittedly, if the distribution were flat (also known as a uniform distribution), then both methods would divide the cases similarly.</p>
<p>By the way, to see what the actual ranges of the quintiles are (this depends on the data you have), you can do this:</p>
<pre><code>## [1] &quot;(-1.56,-0.387]&quot;   &quot;(-0.387,-0.0771]&quot; &quot;(-0.0771,0.138]&quot;  &quot;(0.138,0.417]&quot;   
## [5] &quot;(0.417,1.39]&quot;</code></pre>
<p>This ends the digression. The reason it is important is that this choice of how to make your level assignments will ultimately change how the map looks, and thus what it communicates. We will have a chance to see this play out next.</p>
</div>
<div id="college" class="section level4 unnumbered">
<h4>College</h4>
<p>We already have a variable called “Bach_plus_prop” which accounts for the proportion of college among adults 25 and over. Let’s see how this actual data set can get mapped. Because this has already gotten complicated enough, I’ve wrapped a couple of steps together into a function called <code>getShapeColors</code>. Feel free to simply ignore this if you already have enough on your mind and just skip to the example of how to use it.</p>
<p>Here’s how you use it:
<img src="carpedatum_files/figure-html/unnamed-chunk-89-1.png" width="90%" style="display: block; margin: auto;" /></p>
<p>Hallelujah, we finally have made an image of something. Notice that the output of the <code>getShapeColors</code> functions contains three elements (it is technically a list): values (colors values for each geographic area), legend (text for the legend, including the ranges of values), and palette (these are the colors that go into the len).</p>
<p>The input of <code>getShapeColors</code> is the data you want to visualize as well as the number of levels. In this example, we chose 5. By default, the color palette is shades of blue, but as it is writte, you can provide different colors if you like. For example, the Furman report used a color palette called viridis, which ranges from dark blue to yellow. The only modification necessary is to add an argument to the function:</p>
<p><img src="carpedatum_files/figure-html/unnamed-chunk-90-1.png" width="90%" style="display: block; margin: auto;" /></p>
<p>I don’t know exactly how ABCNews made their color palette, but here is my approximation. I played around with the border color and line width as well.</p>
<p><img src="carpedatum_files/figure-html/unnamed-chunk-91-1.png" width="90%" style="display: block; margin: auto;" /></p>
<p>Here is the original again.</p>
<div class="figure" style="text-align: center"><span id="fig:abc-college"></span>
<img src="images/abc_CollegeDegreeNycZip_v02_KA_hpEmbed_17x12_992.jpg" alt="ABCNews visualization" width="80%" />
<p class="caption">
Figure 15.1: ABCNews visualization
</p>
</div>
<p>I hope you agree that it’s pretty close! Did you spot the main difference? Sure, there are a few of them, but notice the legend in the ABCNews figure? ABCNews used fixed ranges for their level cutoffs, whereas we were using quintiles! What if we want custom cut-points that are not quantiles?</p>
<p>I anticipated this desire in the getShapeColors function, so it’s easy enough. Instead of providing a number (e.g, 5) for <code>nbreaks</code>, you provide the actual list of cutpoints. Here it is on its own.</p>
<p><img src="carpedatum_files/figure-html/unnamed-chunk-92-1.png" width="90%" style="display: block; margin: auto;" /></p>
<p>And here are two versions of the same data, mapped side-by-side using different cut-points:</p>
<p><img src="carpedatum_files/figure-html/unnamed-chunk-93-1.png" width="90%" style="display: block; margin: auto;" /></p>
<p>The difference may be subtle, and I believe an argument can be made for either. But all in all, I believe that the level separation by quintiles does a better job in highlighting the difference between the different parts of the city.</p>
<p>This brings us to our next topic, which is comparing COVID-19 incidence maps to maps showing census data (e.g., income, college education, race, etc.)</p>
</div>
<div id="looking-at-two-variables-at-the-same-time" class="section level4 unnumbered">
<h4>Looking at two variables at the same time</h4>
<p>We can borrow the same side-by-side technique as above, but instead of the same data with different cut-points, we can plot two different variables. We’ll use quintiles in both cases.</p>
<p>It turns out that population-adjusted COVID-19 rate is not actually in our data set. We need to make it, but it’s easy.</p>
<p><img src="carpedatum_files/figure-html/unnamed-chunk-94-1.png" width="90%" style="display: block; margin: auto;" /></p>
<p><img src="carpedatum_files/figure-html/unnamed-chunk-95-1.png" width="90%" style="display: block; margin: auto;" /></p>
<p>Now we’re looking at two different variables, both mapped using quintiles as an organizer of zipcode-level data. It definitely seems like one map is almost an inverse of the other. Where COVID rate is high, college rate is low, and vice versa. Is there some way for us to see both variables on the same map at the same time?</p>
<p>Here’s one idea. Suppose we used different colors for each variable, e.g. red and blue, but we used shades from lighter to darker to indicate lowr and higher values. And suppose we made the colors transparent, the way we did when we plotted two histograms on the same plot. When pink and light-blue are both laid over each other, we will see a purplish color. Therefore</p>
<ol style="list-style-type: decimal">
<li>If both variables are high, we will have darker purple</li>
<li>If both variables are low, we will have lighter purple</li>
<li>If one variable is high and the other low, we will see regions of red or blue</li>
</ol>
<p>So what happens if we “add” up the two variable maps this way?</p>
<p><img src="carpedatum_files/figure-html/unnamed-chunk-96-1.png" width="90%" style="display: block; margin: auto;" /></p>
<p>In the case of college education and COVID incidence rates, the variables are negatively associated. Overlaying two color maps, we see red and bluish regions, but we also see some purple stuff.</p>
<p>What would happen if we did the same for two variable with positive association? Let us map COVID-19 incidence against the average household size.</p>
<p><img src="carpedatum_files/figure-html/unnamed-chunk-97-1.png" width="90%" style="display: block; margin: auto;" /></p>
<p>Indeed, in this case, we see a map that is much more purplish overall.</p>
<p>Given the code examples above, you should be able to create your own zipcode maps of the variables in our data set. You can even get more variables using census queries. The problem of visualizing two (or more) variables on a map is still a challenge. The fact is, there are other data visualizations that are probably better suited to that task, even though they don’t have the narrative association with geography. I’m thinking about the lowly scatterplot</p>
</div>
</div>
<div id="scatterplots" class="section level3 unnumbered">
<h3>Scatterplots</h3>
<p>Here are the data from the last two examples visualized using both maps and scatterplots.</p>
<p><img src="carpedatum_files/figure-html/unnamed-chunk-98-1.png" width="90%" style="display: block; margin: auto;" /></p>
<p>The scatterplots on the right side make it easier to see the relationship between the two variables. As average household sizes go up per zipcode, so do COVID rates. As college education goes up, COVID rates go down. Each point in the scatterplot corresponds to a zipcode region, and in fact, the coloring of the points is the same as the coloring of the regions. But the scatterplot has no geographical information.</p>
<p>Along the 1-to-1 line (i.e., a perfect positive and linear relationship), we would have all purple points, with the colors getting darker at high values. The farther away we are from this diagonal, the more red (above the line) or blue (below) the points are. Note that even with a strongly negative relationship (diagonal trend going down to the right), we will still pass through a purple region. These are regions with average values for both variables.</p>

</div>
</div>
</div>



            </section>

          </div>
        </div>
      </div>
<a href="differences-in-athletics.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="sec-randomness.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": null,
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
